// Furniture-Rx QA suite — TECH front (technician tablet). Evidence-based: tech/index.html,
// netlify/functions (_lib/checkout.mjs, validate.mjs), tech/netlify.toml, Doug decisions (misc/).
export default {
  appId: 'furnfx-qa-tech',
  title: 'Furniture-Rx QA — Tech (Technician) Site',
  version: '2026-07-29',
  envs: [
    { id: 'live', label: 'Live', base: 'https://tech.furniturerx.net' },
    { id: 'local', label: 'Localhost (netlify dev)', base: 'http://localhost:8888/tech' }
  ],
  intro: [
    'This is the technician tablet. It sells only two things: the care kits ($49.99 each, paid once) and the Repair Safety Net membership ($19.99/mo, with the first 3 months free). It must NEVER sell a furniture protection plan.',
    'Before paying anything, check with the team that the site is in Stripe TEST mode. Test card: `4242 4242 4242 4242`, any future expiry date, any 3-digit code, any ZIP.',
    'When a case shows a "Test data for this case" box, tap the chips to copy the Technician ID and customer email it made for you. Do not invent your own.',
    'You will need a phone with a camera for the QR cases. A few cases ask you to open the browser developer tools (press F12) and are marked "Technical".',
    'After finishing a sale, tap "Start a new purchase" (or reload the page) before the next case so carts do not carry over.',
    'There is no login on this site, and that is on purpose. One section checks exactly what that does and does not allow.'
  ],
  sections: [
    {
      id: 'landing',
      title: '1 · Landing page & content',
      cases: [
        { id: 'TECH-001', kind: 'happy', role: 'Anonymous', title: 'Page loads with the technician offer',
          steps: ['Open a fresh browser tab and go to {BASE}/.',
            'Look at the top band of the page (the hero area).'],
          expected: 'The headline reads "Your repair\'s done. Keep it that way." Below it you see the Pro care kit at $49.99 and the Repair Safety Net membership at $0 for the first 3 months, then $19.99/mo. The "Shop kits" and "Add membership" buttons are visible, along with a note that you can pay on this device, scan a QR code, or get the link by email.',
          source: 'tech/index.html:1038-1082 (hero); Doug call: tech sells kits + membership' },
        { id: 'TECH-002', kind: 'access', role: 'Anonymous', title: 'No protection plans anywhere on the page',
          steps: ['Scroll the whole page from top to bottom.',
            'Press Ctrl+F to search the page for the words "protection plan", then "$9.99", then "$19.99/mo plan".'],
          expected: 'There is no plan-comparison section, no plan cards, no $9.99 or $19.99 protection-plan pricing, and no coverage configurator. The membership and the care kits are the only things for sale.',
          source: 'Doug decision (tech = kits + membership only); enforced by static.test.mjs:405-407 and e2e-tech.mjs' },
        { id: 'TECH-003', kind: 'happy', role: 'Anonymous', title: 'Membership section content',
          steps: ['Scroll down to the "Repair Safety Net" membership section.',
            'Click the details or terms link inside that section.'],
          expected: 'The card shows $19.99/mo, a list of benefits, an "Add Repair Safety Net · $19.99/mo" button, and a gift-coupon link. The details link opens a membership Terms pop-up (not a dead link).',
          source: 'tech/index.html:1112-1162, memterms modal 1589-1593' },
        { id: 'TECH-004', kind: 'happy', role: 'Anonymous', title: 'Care kits: three kits at $49.99',
          steps: ['Scroll down to the care kits section.'],
          expected: 'There are exactly three kits: Wood, Fabric & upholstery, and Leather. Each is $49.99, each has a plus/minus quantity stepper, and each has "Add to cart" and "Checkout" buttons.',
          source: 'tech/index.html:1238-1355; SKUs CARE-WOOD/FABRIC/LEATHER-001' },
        { id: 'TECH-005', kind: 'happy', role: 'Anonymous', title: 'FAQ opens and closes',
          steps: ['Scroll down to the FAQ section.',
            'Click several questions to open them, then click again to close them.'],
          expected: 'Eight questions expand and collapse. The answers talk about the care kits and the membership, and never quote a yearly protection-plan price.',
          source: 'tech/index.html:1165-1236' },
        { id: 'TECH-006', kind: 'validation', role: 'Anonymous', title: 'Footer legal links are intentionally inactive',
          steps: ['Scroll to the footer at the very bottom of the page.',
            'Try clicking "Terms of service", then "Privacy", then "Accessibility".'],
          expected: 'Those three links do nothing at all: no page change and no error. Note anything different from that.',
          why: 'This is intentional for now; the final legal wording is not ready yet.',
          source: 'tech/index.html:1373-1378; FOOT-1a/1c pending Doug copy' },
        { id: 'TECH-007', kind: 'happy', role: 'Anonymous', title: 'Sticky mobile bar changes with the cart',
          steps: ['Narrow the browser window to phone width (or open the page on a phone).',
            'With an empty cart, look at the sticky bar pinned to the bottom of the screen.',
            'Add one care kit to the cart, then look at that bottom bar again.'],
          expected: 'With an empty cart the bottom bar reads "Add membership". After you add a kit (or the membership) it changes to read "Checkout".',
          source: 'tech/index.html:3439-3453; e2e-tech.mjs §2' },
        { id: 'TECH-008', kind: 'happy', role: 'Anonymous', title: 'Dashboard link shows a QR, does not navigate the tablet',
          steps: ['Open the cart drawer (the cart button in the top-right corner).',
            'Click "My dashboard" (the dashboard link).'],
          expected: 'An overlay appears with a QR code that points the customer to www.furniturerx.net/dashboard. The tablet itself stays on the tech site and does not navigate away.',
          source: 'tech/index.html:1950-1971 (dashqr overlay)' },
        { id: 'TECH-009', kind: 'happy', role: 'Anonymous', title: 'Plan T&C page exists on this site',
          steps: ['Type the address {BASE}/terms/ into the browser and open it directly.'],
          expected: 'A page titled "Furniture-Rx Protection Plan — Terms & Conditions" loads on this same site. It mentions a 30-day renewable term.',
          source: 'tech/terms/index.html; static.test.mjs:418' }
      ]
    },
    {
      id: 'cart',
      title: '2 · Cart & drawer',
      cases: [
        { id: 'TECH-020', kind: 'happy', role: 'Anonymous', title: 'Adding a kit',
          steps: ['On the Wood kit, press the "+" button until the quantity shows 2, then click "Add to cart".',
            'Open the cart drawer (cart button, top-right corner).'],
          expected: 'The drawer shows a Wood kit line at quantity 2, priced $99.98 for that line, and the total matches. The pay button reads "Pay $99.98 once" (a one-time charge, with no monthly part).',
          source: 'tech/index.html:2353 KIT_PRICE, 2445-2456 pay label' },
        { id: 'TECH-021', kind: 'validation', role: 'Anonymous', title: 'Kit quantity caps at 20',
          steps: ['On any kit, press the "+" button over and over, past 20.'],
          expected: 'The quantity never goes above 20. There is no error message; it simply stops climbing.',
          source: 'tech/index.html:3498 client cap; validate.mjs MAX_KIT_QTY=20 → kit_qty_out_of_range' },
        { id: 'TECH-022', kind: 'happy', role: 'Anonymous', title: 'Adding the membership opens the drawer',
          steps: ['Press "Add membership" in the hero area, or "Add Repair Safety Net · $19.99/mo" in the membership section.'],
          expected: 'The cart drawer opens on its own, showing a membership line at $19.99/mo. The pay button reads "Repair Safety Net · $19.99/mo".',
          source: 'tech/index.html:2492-2497 openMembership()' },
        { id: 'TECH-023', kind: 'happy', role: 'Anonymous', title: 'Mixed cart shows both monthly and one-time in the pay label',
          steps: ['Put both the membership and one care kit in the cart.',
            'Open the drawer and read the pay button.'],
          expected: 'The pay button follows the pattern "Pay $X.XX today ($19.99/mo + $49.99 one-time)". The amount charged today is the kits only; the membership starts on its free trial.',
          source: 'tech/index.html:2445-2456; trial: _lib/checkout.mjs:29-30' },
        { id: 'TECH-024', kind: 'edge', role: 'Anonymous', title: 'Cart survives a reload and a closed tab',
          steps: ['With items in the cart, reload the page (press F5).',
            'Then close the tab completely, open a new tab, and go to {BASE}/.'],
          expected: 'The cart still holds the same kits, membership, and quantities both times, exactly as you left them.',
          source: 'localStorage furnfx_cart/furnfx_kits/furnfx_membership; tech/index.html:3459-3496' },
        { id: 'TECH-025', kind: 'edge', tech: true, role: 'Anonymous', title: 'Tampered saved cart is sanitized, not trusted',
          steps: ['This case checks the tablet ignores a faked cart. Press F12 to open developer tools, then click the "Console" tab.',
            'Paste and run: localStorage.setItem("furnfx_kits", JSON.stringify([{sku:"CARE-WOOD-001",qty:999},{sku:"HACK-1",qty:2}]))',
            'Reload the page and open the cart.'],
          expected: 'The Wood kit quantity is brought down to 20 (not 999), and the unknown "HACK-1" item is dropped entirely. The prices show the normal $49.99, never anything the pasted data claimed.',
          source: 'tech/index.html:3454-3496 loadKits/loadCart re-validate untrusted storage' },
        { id: 'TECH-026', kind: 'edge', role: 'Anonymous', title: 'Two tabs, one cart',
          steps: ['Open {BASE}/ in two separate tabs.',
            'Add a kit in the first tab.',
            'Reload the second tab and open its cart.'],
          expected: 'After the reload, the second tab shows the kit you added in the first tab, because both tabs share one cart on this device. Note any stranger behavior you see without reloading, too.',
          source: 'Shared localStorage cart (device-local single source of truth)' },
        { id: 'TECH-027', kind: 'happy', needs: ['email'], role: 'Anonymous', title: 'Email my cart to myself',
          steps: ['With items in the cart, open the drawer and use "Email my cart to myself". Use the email shown in the "Test data for this case" box below.',
            'Check that inbox (and the spam folder).'],
          expected: 'An email arrives listing the cart with the correct prices. If you try it more than 3 times within a minute, it is politely blocked for a short wait.',
          source: 'tech/index.html:3325-3360; email-cart.mjs rate limit 3/60s' }
      ]
    },
    {
      id: 'form',
      title: '3 · Checkout form validations',
      cases: [
        { id: 'TECH-040', kind: 'validation', role: 'Technician', title: 'Empty form names every missing field',
          steps: ['With something in the cart, open the drawer.',
            'Leave every field empty, tick nothing, and try to pay.'],
          expected: 'The pay button stays disabled until you tick the "I read the information above and it is accurate" checkbox. After ticking it and submitting with empty fields, a message lists every missing field (starting with "Missing:"), and the cursor jumps to the first one.',
          source: 'tech/index.html:2479-2491 accuracy gate, 2709-2733 focusFirst' },
        { id: 'TECH-041', kind: 'validation', role: 'Technician', title: 'Name with digits is rejected',
          steps: ['In the name field, type "John 2nd Smith", and fill in the rest of the form correctly.',
            'Try to pay.'],
          expected: 'The sale is blocked before payment, with a message like "Numbers don\'t belong in a name" shown next to the name field.',
          source: 'tech/index.html:2902; server backstop invalid_name (validate.mjs:123-127)' },
        { id: 'TECH-042', kind: 'edge', role: 'Technician', title: 'Unusual but legitimate names are accepted',
          steps: ['In the name field, type "José Núñez-O\'Brien" (accents, a hyphen, an apostrophe).',
            'Then try a short two-word name like "Al Bo".'],
          expected: 'Both names are accepted, because they have no digits and are at least two letters long. Nothing garbles the accents on screen or in the emails that follow.',
          source: 'validate.mjs:123-127 (only rules: non-empty, no digits, len ≥ 2)' },
        { id: 'TECH-043', kind: 'validation', role: 'Technician', title: 'Email format is checked',
          steps: ['In the email field, type "doug@", then "doug@rap", then "doug @rap.com". Try to pay after each one.',
            'Finally type "doug@rap.com".'],
          expected: 'The first three are rejected with an email message shown right at the field. "doug@rap.com" is accepted.',
          source: 'tech/index.html:2621 EMAIL_RE; server invalid_email (validate.mjs:76-77)' },
        { id: 'TECH-044', kind: 'validation', role: 'Technician', title: 'Phone mask and minimum digits',
          steps: ['In the phone field, type "abc", then type "12345".',
            'Then type "5551234567".'],
          expected: 'Letters never appear (the field accepts digits only, and formats them like "(555) 123-4567", up to 10 digits). "12345" is rejected because a phone needs at least 7 digits. The full number is accepted.',
          source: 'tech/index.html:2634-2664; server invalid_phone (validate.mjs:56-63)' },
        { id: 'TECH-045', kind: 'validation', needs: ['associate','email'], role: 'Technician', title: 'Technician ID is enforced by the server, not the browser',
          steps: ['Fill the form correctly (use the customer email in the "Test data for this case" box below), but leave the Technician ID field empty.',
            'Tick the accuracy checkbox and try to pay.'],
          expected: 'KNOWN ROUGH EDGE to confirm: the browser lets you submit, and then the server refuses. The page shows "We couldn\'t start checkout (invalid_associate)." with that raw code, not friendly wording. Write down exactly what you see. If the browser actually blocked you earlier than this, note that too.',
          source: 'Gap: required attr stripped on tech (tech/index.html:2374-2375) vs validate.mjs:164-165' },
        { id: 'TECH-046', kind: 'validation', needs: ['associate','email'], role: 'Technician', title: 'Work order number is also server-enforced',
          steps: ['Fill the form correctly, including the Technician ID from the "Test data for this case" box below, but leave the Work order number empty.',
            'Try to pay.'],
          expected: 'Same pattern: the browser lets the submit through, then the server answers and the page shows "We couldn\'t start checkout (order_required)." with that raw code.',
          source: 'validate.mjs:166 order_required; Doug 15-jul: both IDs required ("so you get credit")' },
        { id: 'TECH-047', kind: 'happy', needs: ['associate','email'], role: 'Technician', title: 'Technician ID sticks to the device',
          steps: ['Complete any purchase (or just fill in the Technician ID from the "Test data for this case" box below and pay for a kit with the test card).',
            'After the success screen, tap "Start a new purchase" and open the form again.'],
          expected: 'The Technician ID field is already filled with the same ID you used, so the technician does not retype it. All the customer fields are blank.',
          why: 'The Technician ID is kept on this device on purpose, so techs do not re-enter it on every sale.',
          source: 'tech/index.html:3275-3288 ASSOC_KEY persistence' },
        { id: 'TECH-048', kind: 'validation', role: 'Technician', title: 'Referral code: live validation, invalid never blocks the sale',
          steps: ['Open the cart drawer and find the "Dealer referral code" field.',
            'Type "NOPE-0000" and tap outside the field.',
            'If the team gave you a real dealer code, try that one too.'],
          expected: 'An unknown code shows "Code not recognized — you can still check out." and you can still pay. A real code shows "Code applied — supporting <dealer name>."',
          source: 'tech/index.html:2601-2624; Doug 15-jul: bad/disabled code = invalid but sale allowed' },
        { id: 'TECH-049', kind: 'happy', role: 'Technician', title: '?ref= link pre-fills the referral code',
          steps: ['Open {BASE}/?ref=NOPE-0000 in a new tab.',
            'Open the cart form and look at the referral code field.'],
          expected: 'The referral code field arrives already filled with `NOPE-0000`, and it shows its validation result without you typing anything.',
          source: 'tech/index.html:2618-2623' },
        { id: 'TECH-050', kind: 'edge', role: 'Technician', title: 'Autofill does not sneak past the rules',
          steps: ['Use the browser\'s autofill (a saved address or contact) to fill the form in one click.',
            'Check every field afterward, then try to pay.'],
          expected: 'The autofilled values go through the same checks: the phone gets re-formatted by the mask, and the email is validated. A half-filled form still cannot pay.',
          source: 'Same client+server rules regardless of input method (validate.mjs)' }
      ]
    },
    {
      id: 'pay',
      title: '4 · Payment: three ways to pay',
      cases: [
        { id: 'TECH-060', kind: 'happy', role: 'Technician', title: 'Exactly three payment options, none about receipts',
          steps: ['With a valid cart and a filled-in form, look at the "Ways to pay" choices near the bottom of the drawer.'],
          expected: 'There are exactly three options: "Pay on this device" (already selected), a QR code option, and email the link. There is no "receipt photo on the customer\'s phone" option.',
          why: 'Receipt photos belong to the in-store kiosk; technician sales need no receipt.',
          source: 'tech/index.html:1536-1543; static.test.mjs:408' },
        { id: 'TECH-061', kind: 'happy', needs: ['associate','email'], role: 'Technician + Customer', title: 'Pay on this device (full happy path)',
          steps: ['Build a cart with the membership plus one Wood kit.',
            'Open the drawer and fill the form using the Technician ID and customer email from the "Test data for this case" box below, plus any work order number such as `WO-1001`.',
            'Choose "Pay on this device", tick the accuracy box, and pay.',
            'On the Stripe page, check the amounts, then pay with the test card.',
            'Wait to return to the site.'],
          expected: 'Stripe shows $49.99 due today plus the membership on a 3-month free trial (then $19.99/mo). After paying, you land back on the tech site (not another web address), on a "Payment received" screen that tells the plan holder to watch their email for sign-in details.',
          source: '_lib/checkout.mjs:29-30 trial 90d, 148-149 return URLs; tech/index.html:1552-1564' },
        { id: 'TECH-062', kind: 'happy', needs: ['email'], role: 'Technician + Customer', title: 'QR handoff to the customer phone',
          steps: ['Start a new purchase with one kit only. Fill the form using the email in the "Test data for this case" box below.',
            'Choose the QR code option and submit.',
            'Scan the QR code with a phone and pay there with the test card.',
            'Watch the tablet screen the whole time.'],
          expected: 'The tablet shows "Waiting for the customer\'s payment" with the QR code and a short typeable link (starting with /p/). After the phone pays, the tablet moves to the success screen on its own within a few seconds (it keeps checking for the payment).',
          source: 'tech/index.html:3134-3153 poll, 3171-3201 handoff view' },
        { id: 'TECH-063', kind: 'happy', needs: ['email'], role: 'Technician + Customer', title: 'Email link handoff',
          steps: ['Start a new purchase and fill the form using the email in the "Test data for this case" box below.',
            'Choose the email option and submit.',
            'Open the email on another device and pay from there.'],
          expected: 'The tablet says the payment link was sent to that address. (If the email cannot be sent, it falls back to showing the QR code instead; note if that happened.) The emailed link opens the Stripe checkout, and after paying, the tablet moves to the success screen.',
          source: 'tech/index.html:3186-3188 email fallback to QR' },
        { id: 'TECH-064', kind: 'edge', role: 'Technician', title: 'Nobody pays: the wait times out politely',
          steps: ['Start a QR code payment and simply do not pay.',
            'Leave the tablet alone for about 3 minutes.'],
          expected: 'After about 3 minutes of checking, it stops and says it still has no payment confirmation. It offers a "Check again" button that resumes checking, plus "Choose another way to pay" and "Start a new purchase".',
          source: 'tech/index.html:3134-3153 (45 ticks × 4 s), 1565-1580' },
        { id: 'TECH-065', kind: 'edge', role: 'Technician', title: 'Distracted tech closes the drawer mid-wait',
          steps: ['Start a QR code payment.',
            'Close the drawer and scroll around the page.',
            'Reopen the cart drawer.'],
          expected: 'Reopening the drawer brings back the waiting screen for that same payment. The sale in progress is not silently forgotten.',
          source: 'tech/index.html:2523-2530 resume poll' },
        { id: 'TECH-066', kind: 'edge', role: 'Customer', title: 'Customer cancels on the Stripe page',
          steps: ['Choose "Pay on this device", then on the Stripe page press the back arrow or cancel.'],
          expected: 'You return to the tech site with the cart still intact (nothing lost), ready to retry or change it. No "Payment received" screen appears anywhere.',
          source: '_lib/checkout.mjs:149 cancel_url ?canceled=1' },
        { id: 'TECH-067', kind: 'edge', role: 'Technician', title: 'Success screen resets itself for the next customer',
          steps: ['Complete any payment and reach the success screen.',
            'Do not touch anything for two minutes.'],
          expected: 'The cart is already empty right after success, and after about two minutes the screen returns to a fresh sale on its own.',
          why: 'This mirrors the in-store kiosk, so the next customer never sees the previous one\'s information.',
          source: 'tech/index.html:3112 (120 s auto-reset), 3156-3165 cart cleared' },
        { id: 'TECH-068', kind: 'edge', role: 'Technician', title: 'Double-tap on the pay button',
          steps: ['With everything valid, tap the pay button twice as fast as you can.'],
          expected: 'Only one checkout starts (one Stripe page, one session). No double charge and no second tab. Record anything else you notice.',
          source: 'Single submit handler; server idempotent per session — record what you observe' },
        { id: 'TECH-069', kind: 'edge', role: 'Technician', title: 'Hammering checkout hits a polite rate limit',
          steps: ['Start a checkout, cancel on the Stripe page, and repeat quickly six or more times within a minute.'],
          expected: 'Around the sixth try the pay button disables with "Too many attempts — please wait Ns and try again." and comes back on its own after the wait.',
          source: 'create-checkout-session.mjs rate limit 5/60s; tech/index.html:2996-3001' },
        { id: 'TECH-070', kind: 'edge', role: 'Customer', title: 'Back button after a successful payment',
          steps: ['After a successful payment, press the browser Back button.'],
          expected: 'You may land back on the Stripe receipt or on the site, but the cart stays empty and no second charge is possible without building a new cart. Note exactly where Back takes you.',
          source: 'Cart cleared on ?paid=1 (tech/index.html:1913-1915, 3156-3164)' }
      ]
    },
    {
      id: 'rules',
      title: '5 · Business rules to verify end-to-end',
      cases: [
        { id: 'TECH-080', kind: 'happy', role: 'Customer', title: 'Membership trial really is 90 days in Stripe',
          steps: ['Buy the membership on its own (no kits) with the test card.',
            'On the Stripe checkout page, before paying, read the schedule carefully.',
            'If you have access to the Stripe dashboard, check the subscription there afterward.'],
          expected: 'Stripe shows $0.00 due today and $19.99/mo starting in 3 months (a 90-day free trial). Nothing is charged today.',
          source: '_lib/checkout.mjs:29-30 trialDaysFor(tech, membership, no plans) = 90; Doug 10-jul decision TECH-2a' },
        { id: 'TECH-081', kind: 'happy', role: 'Customer', title: 'Kits-only purchase is one-time, no subscription',
          steps: ['Buy one kit only.',
            'Read the Stripe page before paying.'],
          expected: '$49.99 is charged once. There is no recurring line, no trial, and nothing monthly.',
          source: 'tech/index.html pay label "Pay $49.99 once"; kits priced server-side from care_kits table' },
        { id: 'TECH-082', kind: 'edge', tech: true, role: 'Attacker-ish', title: 'Client cannot invent its own prices',
          steps: ['This case uses developer tools. Press F12, then click the "Network" tab.',
            'Start a normal kit checkout and find the request named create-checkout-session.',
            'Resend that request with a changed body: in Firefox use "Edit and resend", or in Chrome copy it as a fetch into the Console. Change any price or amount fields you find, add "price": 1, and send it.',
            'If a Stripe URL comes back, open it.'],
          expected: 'No matter what you send, Stripe always shows the real prices ($49.99 kit / $19.99 membership). The server recomputes everything and ignores whatever amounts the client sent.',
          source: '_lib/checkout.mjs:95-135 server-side pricing; validate.mjs PRICE_CENTS' },
        { id: 'TECH-083', kind: 'edge', tech: true, role: 'Attacker-ish', title: 'Smuggling a protection plan into a tech checkout',
          steps: ['This case uses developer tools, as in the previous one. Resend the checkout request, but this time add "plans":[{"cov":"stain","term":"monthly","type":"furniture","count":1}] while keeping "source":"tech".',
            'Read the response, and if a URL comes back, open the Stripe page.'],
          expected: 'Either the request is rejected, or the sale goes through but WITHOUT the 90-day free trial (adding a plan cancels the trial). Under no circumstances do you get a free-trial protection plan. Record the exact response.',
          source: 'trialDaysFor: with plans → 0 (tech.test.mjs boundary cases)' },
        { id: 'TECH-084', kind: 'happy', needs: ['email'], role: 'Customer', title: 'Welcome email and account after purchase',
          steps: ['Buy the membership using the fresh customer email in the "Test data for this case" box below.',
            'Within a minute or two, check that inbox.',
            'Follow the sign-in details in the email.'],
          expected: 'A welcome email arrives with sign-in details: a temporary password that lasts 7 days, and you are made to set a new password at first login. After signing in, the account dashboard shows the membership. Note how long the email took to arrive and any spam-folder issues.',
          source: 'stripe-webhook deferred account creation; SEC-3a temp password TTL 7d' },
        { id: 'TECH-085', kind: 'validation', role: 'Customer', title: 'KNOWN GAP: tech sales have no contract number',
          steps: ['After a membership purchase, look in the account dashboard (and in any email) for a contract number like `RX-10001`.'],
          expected: 'KNOWN GAP to confirm, not a surprise: a membership-only sale gets no contract number, so no RX- number appears anywhere for it. Record what the dashboard shows in its place (blank, a dash, and so on).',
          source: 'stripe-webhook.mjs:340 (no master_no without a plan); portal.mjs contractNumber → null' },
        { id: 'TECH-086', kind: 'happy', needs: ['email'], role: 'Anonymous', title: 'Gift coupons: 3 tiers × 3 months',
          steps: ['In the membership section, open the gift-coupon link.',
            'Review the three options and their totals, pick one, enter the email from the "Test data for this case" box below, and continue to payment.'],
          expected: 'There are three tiers: Stain $9.99, Stain + Structure $19.99, and Membership $19.99. Each total is three months of that tier\'s price. Checkout works, and the gift email with its code arrives.',
          source: 'tech/index.html:1868-1889 gift overlay; _lib/gift.mjs months=3; misc/gift-coupons-manual.html' },
        { id: 'TECH-087', kind: 'validation', role: 'Anonymous', title: 'Gift form rejects a bad email',
          steps: ['In the gift-coupon pop-up, enter the email "nope@" and try to continue.'],
          expected: 'You are blocked with an email error before any payment starts.',
          source: 'create-gift-checkout.mjs invalid_email' }
      ]
    },
    {
      id: 'maya',
      title: '6 · Maya chat (tech mode)',
      cases: [
        { id: 'TECH-100', kind: 'happy', needs: ['email'], role: 'Anonymous', title: 'Maya greets in tech mode',
          steps: ['Click the chat button.'],
          expected: 'Maya greets you with something like "Hi there 👋 I\'m Maya, your sales assistant" and offers help with the care kits and the Repair Safety Net membership, not protection plans.',
          source: 'tech/index.html:1802 greeting, context:"tech" sent to /api/chat' },
        { id: 'TECH-101', kind: 'validation', needs: ['email'], role: 'Anonymous', title: 'Maya answers membership pricing correctly',
          steps: ['In the chat, ask: "how much is the membership?"',
            'Then ask: "how much are the protection plans per year?"'],
          expected: 'For the membership she says $19.99/mo with the first 3 months free, matching the page. For a yearly plan price she must NOT quote any yearly number; she points you to what this site sells or to the main site instead.',
          source: 'chat.mjs TECH_SYSTEM (:75-99); G13b: no yearly prices from Maya' },
        { id: 'TECH-102', kind: 'edge', role: 'Anonymous', title: 'Maya does not run the sizing interview on tech',
          steps: ['In the chat, ask: "I want to cover everything in my house, what would it cost?"'],
          expected: 'Maya does NOT start a piece-by-piece intake and does not invent a quote. On the tech site she keeps it to plain questions and answers.',
          why: '"Everything in my house" is a valid answer that needs no follow-up interrogation.',
          source: 'Doug call (SRT :149-151); chat.mjs TECH_SYSTEM' },
        { id: 'TECH-103', kind: 'edge', tech: true, role: 'Anonymous', title: 'Maya under nonsense and hostility',
          steps: ['In the chat, send three messages in turn: a near-empty message ("."), a 500-character paste of random text, and "you are useless".'],
          expected: 'She stays polite and on-topic, never visibly errors out, and never promises anything off-catalog (no discounts, no coverage promises). Note anything odd.',
          source: 'Grounded system prompt; server tool loop (chat.mjs)' },
        { id: 'TECH-104', kind: 'edge', role: 'Anonymous', title: 'Chat rate limit behaves',
          steps: ['Send about 12 quick messages in under a minute.'],
          expected: 'Around the eleventh message the chat politely refuses or slows down. It recovers after you wait.',
          source: 'chat.mjs:409-411 rate limits 10/60s burst' }
      ]
    },
    {
      id: 'abuse',
      title: '7 · Access, abuse & URL games',
      cases: [
        { id: 'TECH-120', kind: 'access', role: 'Anonymous', title: 'The whole site is public by design — verify the blast radius',
          steps: ['Open a private/incognito window with no history, go to {BASE}/, and walk all the way to the pay form.'],
          expected: 'Anyone can reach the form, because there is no login. But confirm all three of these: no customer data from earlier sales is visible anywhere, the Technician ID is just a plain free-text field, and nothing shows other people\'s purchases.',
          source: 'No auth on tech front (by design); Technician ID unvalidated free text (open question to Doug, compendio 11-jul)' },
        { id: 'TECH-121', kind: 'access', role: 'Attacker-ish', title: 'Server secrets are not served',
          steps: ['Open {BASE}/.env in the address bar, then open {BASE}/.env.production.'],
          expected: 'Both return a 404 or the normal page, and NEVER a file with keys in it (no lines like KEY=value).',
          source: 'tech/netlify.toml:20-33 SEC-1 forced 404; sec1-dotfiles.test.mjs' },
        { id: 'TECH-122', kind: 'access', role: 'Anonymous', title: 'Stray handoff token in the URL',
          steps: ['Open {BASE}/?h=garbage-token-123 in a new tab.'],
          expected: 'The page switches to a phone-handoff view that cannot do anything valid with a garbage token. It should fail safely, with no crash and no way to reach a paid state. Record exactly what shows.',
          why: 'The tech site never creates these handoff codes; they belong to the in-store kiosk.',
          source: 'tech/index.html:37-45, 1905-1907 (?h= phone mode exists in shared code but is out-of-flow on tech)' },
        { id: 'TECH-123', kind: 'access', role: 'Dealer', title: 'KNOWN GAP: portal "Open app" token is ignored on tech',
          steps: ['This needs a portal login for a dealer that is set up for the technician site. From the portal, use "Open app".',
            'Look at the tech address that opens and what the page does with it.'],
          expected: 'KNOWN GAP to confirm: the tech site opens with `?pt=<token>` in the address but ignores it. The page loads as a plain anonymous visitor, with no dealer session, and any sale made now is NOT tied to the dealer automatically (only a typed referral code ties a sale to a dealer). Record what you see.',
          source: 'portal-app-handoff mints ?pt= for tech (portal.mjs:88-96) but tech/index.html never redeems it' },
        { id: 'TECH-124', kind: 'edge', role: 'Anonymous', title: 'Weird URL parameters do nothing harmful',
          steps: ['Open {BASE}/?paid=1 directly, without paying.',
            'Then open {BASE}/?canceled=1, then {BASE}/?ref=<script>alert(1)</script>.'],
          expected: '?paid=1 may show the success screen and clear the (empty) cart, but it cannot invent a real purchase. ?canceled=1 is harmless. The script in ?ref= never runs (no popup); it is treated as a plain, invalid code.',
          source: 'Dynamic text via textContent (project convention); loadCart validates storage' },
        { id: 'TECH-125', kind: 'edge', tech: true, role: 'Technician', title: 'Offline / flaky network during checkout',
          steps: ['Fill in a valid form. Turn off Wi-Fi, or open developer tools (F12) → "Network" tab and set it to "Offline".',
            'Press pay. Then restore the network and try again.'],
          expected: 'A readable error appears, never a frozen button or a silent nothing. Once the network is back, retrying works without rebuilding the cart.',
          source: 'Front surfaces checkout errors verbatim (tech/index.html:3005)' },
        { id: 'TECH-126', kind: 'edge', role: 'Anonymous', title: 'Old device / small screen sanity',
          steps: ['Set the window to 360px wide (in developer tools device mode, for example Galaxy S8).',
            'Walk the full flow: add a kit, open the drawer, fill the form, and reach the ways to pay.'],
          expected: 'No sideways scrolling, no overlapping controls, every button reachable, and the drawer usable with the on-screen keyboard open.',
          source: 'Responsive gate precedent (e2e-responsive covers portal; note tech findings as observations)' }
      ]
    }
  ]
};
