// Furniture-Rx QA suite — Subscription PORTAL. Evidence-based: portal/index.html + portal.js,
// netlify/functions/portal-*.mjs + _lib, Doug decisions (compendio 11-jul, review 17-jul, 18-jul).
// The portal is role-driven; most cases specify the role to log in as.
export default {
  appId: 'furnfx-qa-portal',
  title: 'Furniture-Rx QA — Subscription Portal',
  version: '2026-07-30',
  envs: [
    { id: 'live', label: 'Live', base: 'https://portal.furniturerx.net' },
    { id: 'local', label: 'Localhost (netlify dev)', base: 'http://localhost:8888/portal' }
  ],
  access: {
    note: 'Sign in with the shared test logins below. Each role sees a different portal — that is the point of many cases. For cross-site cases, open the selling front (D2C / kiosk) in a **separate window**.',
    links: [
      { label: 'D2C storefront', urlByEnv: { live: 'https://www.furniturerx.net', local: 'http://localhost:8888' } },
      { label: 'Kiosk', urlByEnv: { live: 'https://kiosk.furniturerx.net', local: 'http://localhost:8888/kiosk' } }
    ],
    credentials: [
      { role: 'RAP admin (everything)', email: 'admin@raptns.com', password: '12345678' },
      { role: 'Dealer owner (Summit Home Furnishings)', email: 'owner@rapqa.com', password: '12345678' },
      { role: 'Store manager (reduced)', email: 'store@rapqa.com', password: '12345678' },
      { role: 'Customer (account.html only, NOT the portal)', email: 'customer1@rapqa.com', password: '12345678' }
    ]
  },
  intro: [
    'The portal is the back office that dealers and RAP staff sign into. What you can see and do depends on which login you use, so most cases tell you exactly which account to sign in with.',
    'RAP admin (admin@raptns.com) sees everything: every dealer and every menu item. Only this login has the two dropdowns at the top of the page, "World" and "Viewing", that switch between the Retail and Technician versions of the portal and choose which dealer you are looking at. This login can manage dealers, generate codes, cancel subscriptions and open the Audit Log.',
    'Dealer owner (owner@rapqa.com) sees one company, Summit Home Furnishings, with all of its stores and staff. It can export lists and see commissions, but it has no Dealer Admin, no Audit Log and cannot generate codes.',
    'Store manager (store@rapqa.com) sees a single store and less of it: no exports, no referral codes, and no Stripe or commission screens.',
    'Many cases are ACCESS cases: the whole point is that a login is BLOCKED from something. For those, "Pass" means the thing was correctly hidden or refused.',
    'The "World" and "Viewing" dropdowns at the top of the page appear only for the RAP admin. Switching World also renames some labels on screen (for example "Dealer" becomes "Company", and "Sales order #" becomes "Workorder #"), and checking that the renaming is correct is itself part of the test.',
    'A few cases are marked technical: they ask you to open the browser developer tools, copy the sign-in token from a network request and send a request by hand. If you are not sure how, ask the team; each case spells out what to paste.'
  ],
  sections: [
    {
      id: 'login',
      title: '1 · Login, sessions & rate limits',
      cases: [
        { id: 'POR-001', kind: 'happy', role: 'Any', title: 'Landing page and login',
          steps: ['Open {BASE}/ while signed out.', 'Sign in with one of the test logins above.'],
          expected: 'The signed-out page shows the welcome banner and a "Become a reseller" button. After you sign in you land on the dashboard, and if you reload the page you stay signed in.',
          source: 'portal/index.html:12-35; portal.js session frx_portal_session' },
        { id: 'POR-002', kind: 'validation', role: 'Any', title: 'Wrong credentials give a uniform error',
          steps: ['Try a real login email with the wrong password.',
            'Try an email that does not exist at all.'],
          expected: 'Both attempts show the exact same message, "Wrong email or password."',
          why: 'Showing one message for both means the portal never reveals whether an email is registered.',
          source: 'auth-login.mjs uniform 401 invalid_credentials' },
        { id: 'POR-003', kind: 'access', role: 'Customer', title: 'A normal customer account cannot enter the portal',
          steps: ['If you have a plain customer login (one created by a normal storefront or kiosk purchase, e.g. customer1@rapqa.com), try signing in here.'],
          expected: 'The portal refuses with "This account has no portal access."',
          why: 'Customer accounts are not portal users; they belong on the customer sign-in page.',
          source: 'portal-me.mjs:35 not_portal_user 403' },
        { id: 'POR-004', kind: 'edge', role: 'Any', title: 'Login rate limit (per IP and per account)',
          steps: ['On purpose, fail the login six or more times quickly using the same email.'],
          expected: 'Around the sixth attempt you get "Too many attempts. Please wait a moment and try again." Repeated wrong tries against one account keep getting throttled even from a different network or computer.',
          why: 'There are two limits at once: one on how fast a single computer can try, and one on how many times a single account can be targeted, so switching networks does not get around it.',
          source: 'auth-login.mjs:43,63 (SEC-2 dual rate limit)' },
        { id: 'POR-005', kind: 'edge', tech: true, role: 'Any', title: 'Expired / tampered session is handled',
          steps: ['This checks that a broken sign-in is cleaned up rather than left half-loaded. After signing in, press F12 to open developer tools and click the "Console" tab.',
            'Paste and run: localStorage.setItem("frx_portal_session", "{}"), then reload the page.'],
          expected: 'You are returned to the landing/login page cleanly with "Session expired. Please sign in again.", not into a broken half-loaded portal.',
          source: 'portal.js:41-47 session validation, 92-93' }
      ]
    },
    {
      id: 'access',
      title: '2 · Role access matrix (deny tests)',
      cases: [
        { id: 'POR-020', kind: 'access', role: 'Admin', title: 'Admin sees every tab and both selectors',
          steps: ['Sign in as the RAP admin (admin@raptns.com). Read the items in the left menu, then look at the top of the page.'],
          expected: 'The left menu includes Dashboard, Sales Stats, Subscribers, Referral Codes, Stripe Account, Dealer Admin, Pricing & Plans and Audit Log. At the top of the page you see the "World" and "Viewing" dropdowns.',
          source: 'index.html data-roles; portal.js:149-156 #hdr-admin' },
        { id: 'POR-021', kind: 'access', role: 'Org', title: 'Dealer is denied admin-only tabs',
          steps: ['Sign in as the Dealer owner (owner@rapqa.com). Read the left menu.',
            'Check whether Dealer Admin, Pricing & Plans, Audit Log and the top "World"/"Viewing" dropdowns are there.'],
          expected: 'Dealer Admin, Pricing & Plans, Audit Log and the "World"/"Viewing" dropdowns are all missing. Dashboard, Sales Stats, Subscribers, Referral Codes and Stripe Account are still there.',
          source: 'data-roles="admin" on those items; portal.js:149-156' },
        { id: 'POR-022', kind: 'access', role: 'Sub', title: 'Store role is reduced (no export/referral/stripe)',
          steps: ['Sign in as the Store manager (store@rapqa.com). Read the left menu and open Subscribers.',
            'Look for an "Export to Excel" button, a "Referral Codes" menu item, and a "Stripe Account" menu item.'],
          expected: 'There is no Export button, no Referral Codes and no Stripe Account. The "Your access" card describes a reduced store view. Subscribers is still visible.',
          why: 'Seeing the company-wide subscriber list is intentionally allowed even for the store role.',
          source: 'deriveScope: sub excluded from export/api/stripe/referral (_lib/portal.mjs:42)' },
        { id: 'POR-023', kind: 'access', tech: true, role: 'Org', title: 'Server enforces export deny, not just the UI',
          steps: ['This checks the server blocks the export for a store role even if someone bypasses the button. The Dealer owner is allowed to export, so sign in as the Store manager (store@rapqa.com) for the real test.',
            'Open developer tools (F12), click the "Console" tab, and run: fetch("/api/portal-exports",{method:"POST",headers:{Authorization:"Bearer "+JSON.parse(localStorage.frx_portal_session).access_token,"Content-Type":"application/json"},body:"{}"}).then(r=>r.status).then(console.log)'],
          expected: 'The request comes back 403. The export is refused by the server for a store role, not just hidden in the menu.',
          source: 'portal-exports.mjs:31 assertCanExport' },
        { id: 'POR-024', kind: 'access', tech: true, role: 'Sub', title: 'Referral generation is admin-only on the server',
          steps: ['This checks the server blocks code creation even if the button is bypassed. Signed in as the Store manager (or the Dealer owner), open developer tools, click the "Console" tab, and run: fetch("/api/portal-referral-codes",{method:"POST",headers:{Authorization:"Bearer "+JSON.parse(localStorage.frx_portal_session).access_token,"Content-Type":"application/json"},body:JSON.stringify({org_id:"any"})}).then(r=>r.status).then(console.log)'],
          expected: 'The request comes back 403. Only the RAP admin can create referral codes, and the server enforces it.',
          source: 'portal-referral-codes.mjs:77 canReferralCreate' },
        { id: 'POR-025', kind: 'access', tech: true, role: 'Org', title: 'Cross-tenant data returns 404, not 403',
          steps: ['Sign in as the Dealer owner. Open one of your own customer records and note the id in its address.',
            'This checks a dealer cannot fish for another dealer\'s records. In developer tools, call /api/portal-customer for an id you believe belongs to ANOTHER dealer (or a random id).'],
          expected: 'The request comes back 404 (not found), not 403 (forbidden). A dealer cannot use the difference between those answers to discover that another dealer\'s record exists.',
          source: 'readOrgScope → 404 (_lib/portal.mjs:126); portal-customer.mjs:48' },
        { id: 'POR-026', kind: 'access', role: 'Org', title: 'Stripe subscription id is hidden from dealers',
          steps: ['Sign in as the RAP admin, open any customer record, and note the "Stripe subscription" value.',
            'Sign in as the Dealer owner, open the SAME customer record, and compare that value.'],
          expected: 'The admin sees the real Stripe id. The dealer sees it masked as "•••• •••• •••• (admin only)" or a dash. The real id is never sent to a dealer, not even in the network data.',
          source: 'ADMIN_ONLY_FIELDS + stripe_sub_display (_lib/portal.mjs:31, 262-266); Doug 17-jul item 13' },
        { id: 'POR-027', kind: 'access', tech: true, role: 'Sub', title: 'KNOWN GAP: Pricing & Plans data has no server guard',
          steps: ['This documents a known gap. Sign in as the Store manager, open developer tools, click the "Console" tab, and run: fetch("/api/portal-plans",{headers:{Authorization:"Bearer "+JSON.parse(localStorage.frx_portal_session).access_token}}).then(r=>r.status).then(console.log)'],
          expected: 'Known gap to confirm: the "Pricing & Plans" menu item is admin-only, but this endpoint still answers 200 for any signed-in user. It only returns the two display-only plans and prices, so no sensitive data leaks, but the menu label suggests it should be admin-only. Record the status you get.',
          source: 'Gap: portal-plans.mjs:23-24 no assertAdmin vs index.html:118 data-roles="admin"' },
        { id: 'POR-028', kind: 'access', tech: true, role: 'Any', title: 'Audit log is admin-only on the server',
          steps: ['This checks the audit log is refused to non-admins on the server. Signed in as the Dealer owner or Store manager, open developer tools, click the "Console" tab, and run: fetch("/api/portal-audit",{headers:{Authorization:"Bearer "+JSON.parse(localStorage.frx_portal_session).access_token}}).then(r=>r.status).then(console.log)'],
          expected: 'The request comes back 403 for anyone who is not the RAP admin.',
          source: 'portal-audit.mjs:21 assertAdmin' }
      ]
    },
    {
      id: 'world',
      title: '3 · World, Viewing & label switching (admin)',
      cases: [
        { id: 'POR-040', kind: 'happy', role: 'Admin', title: 'Switching World relabels the whole portal',
          steps: ['Sign in as the RAP admin. Set the top "World" dropdown to "Retail". Note these labels: "Dealer Admin", "Sales order #", "Delivery date", "Dealer name".',
            'Switch the "World" dropdown to "Technician" and read the same labels again across the menu, the Subscribers columns and a customer record.'],
          expected: 'In Technician mode the labels change to "Company Admin", "Workorder #", "Service date", "Company name" and "Technician". Retail-only blocks such as "By sales associate" disappear.',
          source: 'LEX map portal.js:108-123; PORT-19A' },
        { id: 'POR-041', kind: 'happy', role: 'Admin', title: 'Viewing = a dealer scopes every screen',
          steps: ['Sign in as the RAP admin. Set the top "Viewing" dropdown to a single dealer.',
            'Open Dashboard, Sales Stats and Subscribers.',
            'Set "Viewing" to "All resellers" and compare.'],
          expected: 'With one dealer chosen, every figure and row is for that dealer only. With "All resellers" the numbers add up across dealers. The header label reads "Dealer ID #..." (or "Company ID" in Technician mode).',
          source: 'readOrgScope admin filter; portal.js:159-162' },
        { id: 'POR-042', kind: 'happy', role: 'Admin', title: 'Rollup exclusion hides a demo dealer from "All"',
          steps: ['Sign in as the RAP admin, set "Viewing" to "All resellers", and note the totals.',
            'Open Dealer Admin for a demo or pilot dealer and turn OFF "Include in admin reports".',
            'Go back to the Dashboard with "Viewing" set to "All resellers" and compare; then set "Viewing" to that dealer on its own.'],
          expected: 'With the switch off, that dealer drops out of the "All resellers" totals, but viewing that dealer on its own still shows all of its data (nothing is deleted). RAP direct sales are not affected.',
          source: 'PORT-21 include_in_rollups; _lib/portal.mjs:59-76' },
        { id: 'POR-043', kind: 'happy', role: 'Admin', title: 'Open app (SSO) needs a dealer chosen',
          steps: ['Sign in as the RAP admin. With "Viewing" set to "All resellers", use "Open kiosk signed in".',
            'Now pick one dealer in "Viewing" and try "Open kiosk signed in" again.'],
          expected: 'With "All resellers" it only offers a plain public kiosk link, not a signed-in one. With a single dealer chosen it opens the kiosk already signed in as that dealer.',
          source: 'portal.js:829-833' }
      ]
    },
    {
      id: 'stats',
      title: '4 · Dashboard & Sales Stats',
      cases: [
        { id: 'POR-060', kind: 'happy', role: 'Any', title: 'Dashboard stat cards',
          steps: ['Open the Dashboard.'],
          expected: 'You see four stat cards: Active subscriptions (with "N new this month"), Monthly value, Cancellation rate (with an up/down arrow), and Commission (mo). Below them is a recent-activity list of the latest eight subscriptions, each with a short date, contract number, associate and an Active or Cancelled pill.',
          source: 'PORT-16; index.html:135-140; _lib/stats.mjs:91-104' },
        { id: 'POR-061', kind: 'happy', role: 'Any', title: 'Sales Stats period selector',
          steps: ['Open Sales Stats. Step through the period buttons: All, Year, Month, Today, Custom range.',
            'For Custom range, set a start and an end date.'],
          expected: 'The cards recalculate for each period. A sale dated on the custom end date is included in the count. If you pick an invalid period it quietly falls back to Month.',
          source: 'portal-stats.mjs:38-44; index.html:169-176' },
        { id: 'POR-062', kind: 'happy', role: 'Any', title: 'Program cards and by-location / by-associate minicards',
          steps: ['On Sales Stats, look at the two program cards: $9.99 Stain and $19.99 Stain + Structure.',
            'Scroll the "By location" and "By associate" rows sideways.'],
          expected: 'Both program cards show "Active". The "By location" and "By associate" rows always fill to five cards per row (with blank fillers) and scroll sideways, with a visible scrollbar and drag-to-scroll.',
          source: 'PORT-24A; portal.js:474-479, 522-532' },
        { id: 'POR-063', kind: 'edge', role: 'Admin', title: 'Big numbers and long labels do not break layout',
          steps: ['Sign in as the RAP admin and set "Viewing" to "All resellers" (the biggest set of data).',
            'Open the Dashboard and Sales Stats and look for text spilling out of cards, clipped words, or cards broken by very long dealer or associate names.'],
          expected: 'Everything fits. Big numbers and long names wrap or trim neatly, and the page never scrolls sideways.',
          source: 'PORT-26 responsive; e2e-responsive fixtures use extreme names' }
      ]
    },
    {
      id: 'subs',
      title: '5 · Subscribers & Customer Record',
      cases: [
        { id: 'POR-080', kind: 'happy', role: 'Any', title: 'Subscribers table, sorting and filters',
          steps: ['Open Subscribers. Click the column headers (Start, Program, Name, Pmts, Contract #, Status) to sort, and click again to reverse the order.',
            'Use the search box (by name or contract number) and the store, associate and date filters. Change the page size between 50, 100 and 250.'],
          expected: 'Sorting works in both directions and the filters narrow the list. The footer reads "Showing 1-N of M". Above the table is a note about "30 days from start" and the "RX-#####-NN" contract format.',
          source: 'PORT-24B; portal.js:857-898; index.html:207,227' },
        { id: 'POR-081', kind: 'happy', role: 'Any', title: 'SR column reflects open service requests',
          steps: ['Find a subscriber that has an open service request (or create one first, then come back).',
            'Look at the "SR" column and click its pill.'],
          expected: 'A subscriber with an open request shows an "SR · open" pill in that column; one with none shows a dash. Clicking the pill opens that customer record.',
          source: 'Doug 17-jul items 4-5; portal.js:925-933' },
        { id: 'POR-082', kind: 'happy', role: 'Any', title: 'Customer Record fields and numbers',
          steps: ['Open any customer record.'],
          expected: 'The header shows the master number "RX-#####" and the active "RX-#####-NN". The details block lists contact, address, start date, payments, program, sales order (or Workorder) number, delivery (or service) date, associate, dealer/store, a receipt link, an accepted-terms link, and the Stripe subscription (masked for dealers). The checkout summary always has content, even when it falls back to a synthesized line.',
          source: 'PORT-5/19B/24C; portal.js:1043-1044; _lib/portal.mjs:223-231 (Doug 17-jul item 15)' },
        { id: 'POR-083', kind: 'validation', role: 'Any', title: 'Related purchases block removed from the UI',
          steps: ['In a customer record, look for any "Related purchases" section.'],
          expected: 'There is no "Related purchases" section anywhere in the record. Confirm it is absent.',
          source: 'Doug 17-jul item 9; no block in portal/index.html' },
        { id: 'POR-084', kind: 'happy', role: 'Any', title: 'Service requests inside the record',
          steps: ['In a customer record, look at the list of the last five service requests.',
            'Create a new one: the form comes prefilled with the contract, contact and name; choose the category "Contact customer"; add a note; submit.'],
          expected: 'A new service request is created with a number like "SR-#####", status Open, and a history line "Request received by RAP\'s service center". It shows up in the list. The category menu lets you pick only one at a time (choosing one clears the others).',
          source: 'PORT-24C; portal-service-requests.mjs:56-69; index.html:307-311' },
        { id: 'POR-085', kind: 'happy', role: 'Any', title: 'Resolve a service request',
          steps: ['With a service request open from the list, tick the "Resolved (close)" checkbox and submit.'],
          expected: 'The request flips to Closed. If you try to resolve without first picking a request from the list, you get "Pick a service request from the list to resolve…".',
          source: 'portal-service-requests.mjs:88-90; portal.js:611-617' },
        { id: 'POR-086', kind: 'validation', role: 'Any', title: 'Service request needs a contract and a note',
          steps: ['Start a new service request form, then clear either the contract number or the note and submit.'],
          expected: 'It is blocked with "Add a contract # and a request before submitting." Nothing is created, and no service-request number is used up.',
          source: 'validateServiceRequest invalid_contract / invalid_body_text' },
        { id: 'POR-087', kind: 'access', tech: true, role: 'Org', title: 'SEC-3b: cannot file an SR on another dealer\'s contract',
          steps: ['Sign in as the Dealer owner. This checks the server refuses to file a request against another dealer\'s contract. In developer tools, click the "Console" tab and send a POST to /api/portal-service-requests with a contract number you believe belongs to ANOTHER dealer, for example the body {"contract_number":"RX-19999","body":"x"}.'],
          expected: 'The request comes back 404 (not found). The ownership check runs before anything is created, so no request is filed under the wrong account.',
          why: 'This behavior closed a real security hole.',
          source: 'SEC-3b portal-service-requests.mjs:32-54' }
      ]
    },
    {
      id: 'actions',
      title: '6 · Quick actions & cancellation',
      cases: [
        { id: 'POR-100', kind: 'happy', role: 'Admin', title: 'Resend dashboard link and T&C',
          steps: ['Sign in as the RAP admin, open a customer record, click "Resend dashboard link" and confirm in the pop-up.',
            'Then click "Resend T&C".'],
          expected: 'Each one shows a confirm pop-up and then a result pop-up ("Link sent" / "Terms sent"), and the customer email actually receives them. "Print T&C" opens the terms page in a new tab.',
          source: 'portal-resend-link.mjs; portal.js:1000-1020; Doug 17-jul item 14' },
        { id: 'POR-101', kind: 'access', role: 'Org', title: 'Cancel subscription is visible to all but works only for admin',
          steps: ['Sign in as the Dealer owner, open a customer record and click "Cancel subscription".',
            'Then sign in as the RAP admin and do the same on a test or demo subscription.'],
          expected: 'As the dealer it shows "Admins only" and nothing happens on the server. As the admin it schedules the cancellation for the end of the billing period and records the action. It stays graceful even when Stripe cannot be reached, as with demo subscriptions.',
          source: 'portal-cancel-subscription.mjs assertAdmin + fail-soft; Doug 17-jul item 14' },
        { id: 'POR-102', kind: 'validation', tech: true, role: 'Admin', title: 'Bad contract on quick actions',
          steps: ['This checks the server rejects bad input. In developer tools, call /api/portal-resend-link with the contract "NOT-A-CONTRACT".'],
          expected: 'It returns 400 (invalid contract). A properly formatted but unknown or out-of-scope contract returns 404 instead.',
          source: 'portal-resend-link.mjs:40-53' }
      ]
    },
    {
      id: 'commissions',
      title: '7 · Stripe Account: commissions & reconciliation',
      cases: [
        { id: 'POR-120', kind: 'happy', role: 'Org', title: 'Commission totals and the reinsurance split',
          steps: ['Sign in as the Dealer owner (or as the RAP admin with a dealer chosen in "Viewing") and open Stripe Account.'],
          expected: 'The subtitle states the model: "$2 Stain / $8 Stain+Structure per payment, with your Stripe/reinsurance split." There are three cards: Total cash, To commission (your Stripe), and To reinsurance. No gross RAP revenue figure ever appears.',
          source: 'PORT-8/24D; index.html:361-369; portal-commissions.mjs (no gross revenue, HARD)' },
        { id: 'POR-121', kind: 'happy', role: 'Admin', title: 'Per-dealer override changes the split',
          steps: ['This needs a dealer that has a custom commission split (for example 400/400 on Stain + Structure). Ask the team which dealer to use.',
            'Open that dealer\'s Stripe Account and look at one Stain + Structure payment row.'],
          expected: 'For that dealer, a Stain + Structure payment splits 400¢ to Stripe and 400¢ to reinsurance instead of the usual 800/0. Ordinary dealers show $2/$8 with reinsurance at 0.',
          source: '_lib/commissions.mjs pickRate precedence; test-guide-portal-fase3 step 5.3' },
        { id: 'POR-122', kind: 'happy', role: 'Org', title: 'Reconciliation table (Subscribers clone)',
          steps: ['On Stripe Account, look at the reconciliation table and its date filter.'],
          expected: 'The columns are Start, Name, Contract #, Status, Stripe payment #, Payment date, and a View link to the customer record. Rows with no payment show a dash, never a made-up number. The date filter works on the payment date, not the start date.',
          source: 'Doug 17-jul item 20; portal-reconciliation.mjs:70-76' },
        { id: 'POR-123', kind: 'validation', role: 'Org', title: 'Membership/kit payments earn no commission',
          steps: ['Find a membership-only or kit-only sale in the reconciliation table.'],
          expected: 'It earns $0 commission (only the two protection plans pay $2/$8). A sale with no dealer attached earns nothing either, counting as RAP direct.',
          source: '_lib/commissions.mjs unknown SKU → no commission' },
        { id: 'POR-124', kind: 'validation', role: 'Any', title: 'KNOWN GAP: no clawback on cancellation',
          steps: ['As the RAP admin, cancel a subscription that had at least one commissioned payment, then look at commissions again.'],
          expected: 'Known gap to confirm: cancelling does not reverse any past commission rows (there is no clawback). Note the behavior; it is expected, not a bug to fix on the spot.',
          source: 'Gap: no clawback anywhere in _lib/commissions.mjs' }
      ]
    },
    {
      id: 'referral',
      title: '8 · Referral codes',
      cases: [
        { id: 'POR-140', kind: 'happy', role: 'Admin', title: 'Generate a referral code for a dealer',
          steps: ['Sign in as the RAP admin, set "Viewing" to a dealer, open Referral Codes, type a label, and click Generate.'],
          expected: 'A code appears such as "ABC-2K4M" (a three-letter dealer prefix plus four characters from an alphabet with no 0, O, 1 or I). "Copy kiosk link" and "Copy online link" produce addresses ending in ...kiosk.furniturerx.net/?ref=CODE and ...furniturerx.net/?ref=CODE.',
          source: 'PORT-9; _lib/referral.mjs:34-42; portal.js:709-731' },
        { id: 'POR-141', kind: 'happy', role: 'Org', title: 'Dealer can view codes and their metrics',
          steps: ['Sign in as the Dealer owner and open Referral Codes.'],
          expected: 'The dealer sees its codes with Uses, Attributed subs, Credit earned and Status, but there is no Generate button.',
          why: 'Only the RAP admin can create codes.',
          source: 'canReferralView (org) vs canReferralCreate (admin only)' },
        { id: 'POR-142', kind: 'happy', role: 'Any', title: 'Metrics reflect real attribution',
          steps: ['Take a code and make a storefront or kiosk purchase using it (either by adding ?ref=CODE to the store address, or by typing the code at checkout).',
            'Go back to Referral Codes and refresh.'],
          expected: 'For that code, Uses (leads) and Attributed subs go up, and Credit earned reflects the commission from those subscriptions.',
          source: 'referralStats (_lib/referral.mjs:83-99)' },
        { id: 'POR-143', kind: 'validation', role: 'Any', title: 'A disabled code does not block the sale',
          steps: ['Ask an admin to switch a code or its dealer OFF, or use a code that belongs to a disabled dealer.',
            'Try to buy on the D2C store using that code.'],
          expected: 'The purchase still completes, just with no dealer credited (the code is treated as invalid).',
          why: 'A disabled code never stops a sale; contrast this with a disabled dealer selling through the kiosk session, which IS blocked.',
          source: 'Doug 15-jul decision; _lib/referral.mjs:45-49' }
      ]
    },
    {
      id: 'dealeradmin',
      title: '9 · Dealer Admin (admin only)',
      cases: [
        { id: 'POR-160', kind: 'happy', role: 'Admin', title: 'Edit a dealer record',
          steps: ['Sign in as the RAP admin, set "Viewing" to a dealer, and open Dealer Admin.',
            'Edit the dealer name and head-office address, set the kiosk access start and end dates, and Save.'],
          expected: 'It saves with a "Record saved" message. The Dealer RAP ID and FurnitureRx Account ID cannot be edited. With no dealer chosen it says "Pick a reseller in Viewing…".',
          source: 'PORT-18; portal-dealeradmin.mjs whitelist excludes rap_id; portal.js:271-282' },
        { id: 'POR-161', kind: 'happy', role: 'Admin', title: 'The three dealer toggles',
          steps: ['In Dealer Admin, flip "Sell through kiosk", "Dashboard access" and "Include in admin reports" and watch the messages.'],
          expected: 'Each toggle saves right away ("Enabled" / "Disabled"). Turning "Sell through kiosk" off later blocks that dealer\'s signed-in kiosk sales; turning "Include in admin reports" off removes them from the "All resellers" totals.',
          source: 'portal.js:452-461; selling_enabled / dashboard_enabled / include_in_rollups' },
        { id: 'POR-162', kind: 'happy', role: 'Admin', title: 'Login actions (reset / invite), no password shown',
          steps: ['In Dealer Admin, find the login row, confirm the prefilled login email, then use "Reset password" and "Resend invite".'],
          expected: 'Both send emails, and the screen states "No password is stored or shown". Trying with the email empty says "Type the login email first."',
          source: 'portal-dealer-login-action.mjs; portal.js:465' },
        { id: 'POR-163', kind: 'happy', role: 'Admin', title: 'Terms & conditions per plan SKU (PORT-25)',
          steps: ['In Dealer Admin, find the terms & conditions rows for the two plans (Stain and Stain + Structure).',
            'For one, set a terms version and a document link and Save. Then click "Use generic".'],
          expected: 'Saving shows "Overriding generic <version>". "Use generic" switches it back to "Using generic <version>" (or "No generic set"). Nothing is deleted; rows are only turned on or off.',
          source: 'PORT-25 Doug 18-jul; portal-plan-terms.mjs; portal.js:320-351' },
        { id: 'POR-164', kind: 'happy', role: 'Admin', title: 'Sales-mode link management (KIOSK-22)',
          steps: ['In Dealer Admin, find the "Sales-mode link" box (near Access & credentials).',
            'Generate a link, copy it, download its QR code, then Regenerate, then Disable (confirming the warning pop-up).'],
          expected: 'With no link yet, a warning banner reads "No sales-mode link yet". Generate shows a read-only address plus a QR code inline and a Download QR button. Regenerate kills the old link at once. Disable is behind a confirm pop-up warning that the "current link and QR will stop working".',
          source: 'KIOSK-22; index.html:454-475; portal.js:355-436' },
        { id: 'POR-165', kind: 'access', tech: true, role: 'Org', title: 'Dealer Admin actions are server-guarded',
          steps: ['Sign in as the Dealer owner. This checks a dealer cannot edit dealer records or make sales-mode links by calling the server directly. In developer tools, send a POST to /api/portal-dealeradmin (or /api/portal-sales-mode) with any body.'],
          expected: 'The request comes back 403 (forbidden). A dealer cannot edit dealer records or create sales-mode links even by calling the server directly.',
          source: 'assertAdmin in portal-dealeradmin / portal-sales-mode / portal-plan-terms' }
      ]
    },
    {
      id: 'exports',
      title: '10 · Exports, audit & pricing',
      cases: [
        { id: 'POR-180', kind: 'happy', role: 'Org', title: 'Export subscribers to CSV (filtered)',
          steps: ['Sign in as the Dealer owner, open Subscribers, apply a filter (for example one store or a date range), then click "Export to Excel".'],
          expected: 'You get a CSV of only the filtered rows, with columns First, Last, Program, Start, End, Payments, Associate, Contract # and Status. If nothing matches, it says "No rows to export…".',
          source: 'Doug 17-jul item 7; portal-exports.mjs' },
        { id: 'POR-181', kind: 'edge', role: 'Admin', title: 'CSV formula injection is neutralized (SEC-3c)',
          steps: ['This needs a customer whose name starts with a formula character. If you can, set a test customer\'s name to begin with "=" (or find one that already does).',
            'Export the list and open the CSV in Excel or Google Sheets.',
            'If you cannot create such data, mark this N/A and note why.'],
          expected: 'A cell that starts with =, +, -, @ (or a tab or carriage return) shows as plain text (with a leading apostrophe) and is never run as a formula. Ordinary values like "Protection+", "RX-10017-12" or dates are unaffected.',
          source: 'SEC-3c _lib/portal.mjs:288-313' },
        { id: 'POR-182', kind: 'happy', role: 'Admin', title: 'Audit log records changes',
          steps: ['Sign in as the RAP admin and do a few actions: edit a dealer, generate a code, run an export, cancel a demo subscription.',
            'Open Audit Log and filter by category (Change / Export / Access).'],
          expected: 'Each action shows up with When, Actor, Role, Action, Target and Details (for example "Exported subscribers · CSV · N rows · PII included").',
          why: 'Views and logins are deliberately not recorded in the audit log; note that.',
          source: 'portal-audit.mjs; _lib/portal.mjs:314-319; audit write points' },
        { id: 'POR-183', kind: 'happy', role: 'Admin', title: 'Pricing & Plans is display-only',
          steps: ['Open Pricing & Plans.'],
          expected: 'Two plans are listed: Protection (Stain) $9.99 and Protection+ (Stain + Structure) $19.99, both marked non-editable. A footer explains that the plan itself is the key, not the type of piece.',
          source: 'portal-plans.mjs:33-43; Doug 15-jul "just show it"' }
      ]
    },
    {
      id: 'inquiries',
      title: '11 · Public reseller inquiry',
      cases: [
        { id: 'POR-200', kind: 'happy', role: 'Anonymous', title: 'Become a reseller form',
          steps: ['While signed out on {BASE}/, open "Become a reseller", fill in name, email, world and phone, then submit.'],
          expected: 'You see "Thanks — we\'ll be in touch." and the form clears. Later, signed in as the RAP admin, the inquiry appears in the admin inquiries list with status New.',
          source: 'portal-inquiries.mjs; validateInquiry' },
        { id: 'POR-201', kind: 'validation', role: 'Anonymous', title: 'Inquiry validation and honeypot',
          steps: ['Submit with a bad email and watch what happens. Then submit quickly six times in a row and watch again.',
            'Optional technical step: in developer tools, fill the hidden "company_url" field from the Console and submit.'],
          expected: 'A bad email is rejected ("check your details"). Rapid submits are rate-limited ("please wait a moment"). If the hidden "company_url" field is filled in, the server quietly accepts the submission (200) but throws it away as spam.',
          why: 'The hidden "company_url" field is a spam trap that a real person never sees or fills.',
          source: 'portal-inquiries.mjs:45 honeypot; rate limit 5/60s' }
      ]
    },
    {
      id: 'responsive',
      title: '12 · Responsive & resilience',
      cases: [
        { id: 'POR-220', kind: 'edge', role: 'Any', title: 'Hamburger nav appears at ≤900px',
          steps: ['Shrink the window to about 360px wide (developer tools device mode).',
            'Open the slide-out menu with the hamburger button, tap a menu item, then press Escape.'],
          expected: 'At 900px wide or narrower, a hamburger button opens a slide-out menu over a dark backdrop. Escape closes it, tapping an item closes it, and the keyboard focus moves into the menu when it opens. At 901px and wider the desktop layout is unchanged.',
          source: 'PORT-27; portal.css hamburger; portal.js:205-218' },
        { id: 'POR-221', kind: 'edge', role: 'Admin', title: 'No horizontal overflow anywhere',
          steps: ['At window widths of 360, 390, 768, 1024, 1440 and 1920px, walk through Dashboard, Sales Stats, Subscribers, a customer record, Stripe Account and Dealer Admin.',
            'Watch for the whole page scrolling sideways (a wide table scrolling inside its own box is fine).'],
          expected: 'The page itself never scrolls sideways at any width. Only wide tables scroll, and only inside their own box. Report the exact screen and element for any sideways page scroll.',
          source: 'PORT-26 responsive gate (zero page-level overflow, 3 roles × 7 viewports)' },
        { id: 'POR-222', kind: 'edge', role: 'Admin', title: '1440px matches the approved design',
          steps: ['At exactly 1440px wide, compare the Dashboard and Subscribers against the approved design.'],
          expected: 'They match the approved design exactly; the responsive work must not have shifted the desktop layout.',
          source: 'PORT-26 step 11 (1440 unchanged)' },
        { id: 'POR-223', kind: 'edge', tech: true, role: 'Any', title: 'Session dies mid-use',
          steps: ['While signed in, open developer tools and delete the "frx_portal_session" item, then click into another tab such as Subscribers.'],
          expected: 'The portal notices the session is gone and returns you to the sign-in page, instead of showing empty or broken screens.',
          source: 'portal.js session guard' }
      ]
    },
    {
      id: 'xsite',
      title: '13 · Cross-site: portal ↔ selling fronts',
      cases: [
        { id: 'POR-XS-01', kind: 'access', role: 'Admin', needs: ['email'], title: 'A code generated here counts up after a real purchase',
          openInWindow: 'D2C storefront',
          steps: ['Sign in as the RAP admin. In the top dealer dropdown pick "Summit Home Furnishings", open "Referral Codes", click "Generate code", and copy it (e.g. SUM-7K2M).',
            'Open the D2C storefront in a separate window (the "Open D2C storefront" button above). In its address bar, add `?ref=` followed by the code you copied, and press Enter.',
            'On the store, build a plan and pay with the test card (use the customer email from the Test data box below).',
            'Back in the portal Referral Codes screen (Summit selected), wait a minute or two and refresh.'],
          expected: 'On the store the code shows "Code applied — supporting Summit Home Furnishings." After the sale, that code\'s "Uses" and "Attributed subs" each go up by one here.',
          why: 'The dollar "Credit earned" only moves if commission tracking is switched on in this environment, so $0 there is expected.',
          source: 'portal-referral-codes.mjs generate; index.html ?ref; referralStats _lib/referral.mjs:83-99' },
        { id: 'POR-XS-02', kind: 'happy', role: 'Admin + Dealer', title: 'A kiosk/store sale appears in Subscribers with its associate #',
          openInWindow: 'Kiosk',
          steps: ['Open the Kiosk in a separate window. Make a plain plan sale, typing a memorable associate number such as A-91, and pay with the test card.',
            'In the portal, open "Subscribers" (as the RAP admin with "All" selected, or as the Dealer owner).',
            'Wait a minute or two and refresh.'],
          expected: 'The new subscription appears in the list, showing associate A-91 in the associate column, and the Dashboard "Active subscribers" count reflects it.',
          source: 'stripe-webhook.mjs:273 (associate copied); portal-subscribers.mjs; _lib/portal.mjs:216' },
        { id: 'POR-XS-03', kind: 'access', role: 'Admin', title: 'Turning "Sell through kiosk" off refuses that dealer\'s session sales',
          openInWindow: 'Kiosk',
          steps: ['As the RAP admin, pick "Summit", open Dealer Admin, and turn "Sell through kiosk" OFF.',
            'Generate (or reuse) Summit\'s sales-mode link, open it in the Kiosk window, build a plan and try to pay.',
            'When done, turn "Sell through kiosk" back ON.'],
          expected: 'The checkout is refused and the sale does not complete.',
          why: 'For contrast, the same dealer\'s referral code typed on the plain kiosk would just be ignored while the sale still completes.',
          source: 'portal-dealeradmin selling_enabled; _lib/checkout.mjs:71-79; _lib/referral.mjs:45-49' },
        { id: 'POR-XS-04', kind: 'validation', role: 'Admin + Customer', title: 'Cancelling here does not instantly change the customer dashboard',
          openInWindow: 'D2C storefront',
          steps: ['As the RAP admin, open "Subscribers", click a demo row (e.g. RX-90001) to open the customer record, and click "Cancel subscription", confirm.',
            'In a separate window open the customer sign-in page (the D2C storefront address above, then /account.html), and sign in as customer1@rapqa.com / 12345678.',
            'Look at the plan status.'],
          expected: 'The portal records the cancellation (an audit entry, scheduled for the end of the billing period). Known limitation to confirm: the customer\'s own dashboard still shows the plan as "active" right away, and only changes later when Stripe reports the change. Treat "no immediate change on the customer side" as the correct, expected result and flag it for product review.',
          source: 'portal-cancel-subscription.mjs (Stripe cancel + audit, no DB write); get-my-account.mjs status only' },
        { id: 'POR-XS-05', kind: 'access', role: 'Admin', title: 'KNOWN GAP: portal → Tech-site sign-in does nothing',
          steps: ['This documents a known gap. As the RAP admin, if you have a technician-world dealer, its "Open kiosk signed in" points at the Tech site.',
            'Open a Tech-site address with a "?pt=SOMETOKEN" on the end.'],
          expected: 'The Tech site loads as a plain public page, with no "Selling as" badge and no session, and the "?pt=" is ignored. So signing in from the portal to the Tech site currently does nothing, unlike the kiosk which does sign in. Confirm this gap.',
          source: 'tech/index.html has no ?pt= redeem (contrast kiosk/index.html:2711-2716)' }
      ]
    }
  ]
};
