// Furniture-Rx QA suite — KIOSK front (in-store tablet). v2: evidence hidden from testers,
// explicit navigation, test-data chips (needs), technical flags, credentials, cross-site section.
export default {
  appId: 'furnfx-qa-kiosk',
  title: 'Furniture-Rx QA — In-Store Kiosk',
  version: '2026-07-30',
  envs: [
    { id: 'live', label: 'Live', base: 'https://kiosk.furniturerx.net' },
    { id: 'local', label: 'Localhost (netlify dev)', base: 'http://localhost:8888/kiosk' }
  ],
  access: {
    note: 'Some cases need you to sign into the Subscription Portal in a **separate window** (to generate a sales link, check that a sale arrived, or flip a dealer setting). Use the shared test logins below.',
    links: [
      { label: 'Subscription Portal', urlByEnv: { live: 'https://portal.furniturerx.net', local: 'http://localhost:8888/portal' } }
    ],
    credentials: [
      { role: 'RAP admin (sees everything, makes links)', email: 'admin@raptns.com', password: '12345678' },
      { role: 'Dealer owner (Summit Home Furnishings)', email: 'owner@rapqa.com', password: '12345678' },
      { role: 'Store manager', email: 'store@rapqa.com', password: '12345678' }
    ]
  },
  intro: [
    'The kiosk is the tablet a store associate uses to sell protection plans (Stain $9.99/mo, Stain + Structure $19.99/mo), care kits ($49.99) and the Repair Safety Net membership. It has store-only fields (associate #, sales order #, receipt photo) and four ways to pay, including handing off to the customer\'s phone with a QR code.',
    'Before paying anything, check with the team that the site is in Stripe TEST mode. Test card: `4242 4242 4242 4242`, any future expiry date, any 3-digit code, any ZIP.',
    'When a case shows a "Test data for this case" box, tap the chips to copy the associate # and customer email it made for you — do not invent your own.',
    'You will need a phone with a camera for the QR cases, and something printed (any receipt or page) to photograph.',
    'After finishing a sale, tap "Start a new purchase" (or reload the page) before the next case so carts do not carry over.'
  ],
  sections: [
    {
      id: 'entry',
      title: '1 · Opening the kiosk',
      cases: [
        { id: 'KSK-001', kind: 'happy', role: 'Associate', title: 'The kiosk opens ready to sell, no login',
          steps: ['Open a fresh browser tab and go to {BASE}/.',
            'Look over the page: the two plan cards, the care kits, the membership section, and the cart button in the top-right corner.'],
          expected: 'The page loads and you can start selling without signing in. You do not see any other customer\'s information anywhere on the screen.',
          source: 'kiosk/index.html:2 (kiosk mode built in); no auth by design' },
        { id: 'KSK-002', kind: 'access', role: 'Dealer', title: 'Signing in from the portal shows a "Selling as" badge',
          openInWindow: 'Subscription Portal',
          steps: ['Open the Subscription Portal in a separate window (button above, or the "Access & creds" button in the top bar).',
            'On the portal, click "Log in to your dashboard" and sign in as the Dealer owner (owner@rapqa.com / 12345678).',
            'In the portal\'s left menu, click "⇗ Open kiosk signed in". A kiosk tab opens.',
            'Watch the kiosk\'s web address and the bottom-left corner of the page.'],
          expected: 'The kiosk opens. The long "?pt=..." text disappears from the address by itself within a second. A dark badge appears in the bottom-left reading "Selling as Summit Home Furnishings", with a small "Dashboard ↗" link next to it. In the checkout drawer, the "referral code" field is now hidden (the sale is tied to this dealer automatically).',
          source: 'kiosk/index.html:2705-2722 (badge), 2700-2703 (referral hidden); portal-app-redeem.mjs (12h session)' },
        { id: 'KSK-003', kind: 'access', role: 'Anyone', title: 'A sales-mode link lets you sell with no login',
          openInWindow: 'Subscription Portal',
          steps: ['In a separate window, sign into the portal as the RAP admin (admin@raptns.com / 12345678).',
            'At the top of the portal, in the dealer dropdown that shows "All", choose "Summit Home Furnishings".',
            'In the left menu open "▣ Dealer Admin". Scroll to the "Sales-mode link" box and click "Generate link". Copy the address it shows (it looks like {BASE}/s/ABC123).',
            'Open that /s/... address in a fresh window (or scan its QR with a phone).'],
          expected: 'You land on the kiosk with a "Selling as Summit Home Furnishings" badge, but this time there is NO "Dashboard ↗" link next to it (sales mode must not open the dashboard). Any sale you make now is tied to Summit automatically.',
          source: 'KIOSK-22 (Doug 18-jul); kiosk/index.html:2687-2697; sales-mode-redirect.mjs' },
        { id: 'KSK-004', kind: 'access', role: 'Anyone', title: 'A wrong or switched-off sales link is refused',
          steps: ['Open {BASE}/s/WRONGCODE in a new window.',
            'If you generated a real sales link in the previous case, generate a NEW one in Dealer Admin (the button now says "Regenerate link"), then open the OLD address again.'],
          expected: 'Both show a clean "Sales link not found — check the link, or ask an administrator to generate a new sales-mode link" page. The old link stops working the moment a new one is made.',
          source: 'sales-mode-redirect.mjs:33-58; portal-sales-mode rotate deactivates prior links' },
        { id: 'KSK-005', kind: 'access', role: 'Attacker-ish', tech: true, title: 'A used sign-in link cannot be reused',
          openInWindow: 'Subscription Portal',
          steps: ['Do case KSK-002 once (a successful "Open kiosk signed in"). Right after, from your browser history copy the full kiosk address that contained "?pt=...".',
            'Paste that same "?pt=" address into a NEW private/incognito window.',
            'Separately: from the portal, click "Open kiosk signed in" again but wait more than 2 minutes before opening the link it produced.'],
          expected: 'The sign-in link only works once and expires in about two minutes. Both the reuse and the delayed attempt quietly open the plain kiosk instead — no "Selling as" badge, no dealer session — and never show an error page or reveal a dealer identity.',
          source: 'portal-app-redeem.mjs:31-40 (single-use, race-safe); TTL 120s' }
      ]
    },
    {
      id: 'cart',
      title: '2 · Plans, kits, membership & cart',
      cases: [
        { id: 'KSK-020', kind: 'happy', role: 'Associate', title: 'Plan prices and adding more than one',
          steps: ['Look at the two plan cards: "Stain" and "Stain + Structure".',
            'On the Stain card, press the "+" button a few times to raise the count.'],
          expected: 'Stain is $9.99/mo and Stain + Structure is $19.99/mo, both covering up to $5,000. The "+" button keeps raising the count past two; the price and coverage note update accordingly.',
          source: 'kiosk/index.html:2125-2129; MAX_COUNT=99 (Doug 18-jun)' },
        { id: 'KSK-021', kind: 'validation', role: 'Associate', title: 'Yearly prices are shown but cannot be bought',
          steps: ['If the plan area has a "Monthly / 1 year / 3 years" switch, tap "1 year", then "3 years".',
            'Try to raise the count and to find a Checkout button while on a yearly option.',
            'Switch back to "Monthly".'],
          expected: 'Yearly options display prices for comparison, but the stepper is disabled and there is no way to add a yearly plan to the cart. Only monthly plans can be purchased.',
          why: 'Yearly is intentionally preview-only for now; only monthly is wired for checkout.',
          source: 'kiosk/index.html:2246-2253, 3032-3035; server term_not_supported' },
        { id: 'KSK-022', kind: 'happy', role: 'Associate', title: 'Membership price never changes with the cart',
          steps: ['In the membership section, press "Add Repair Safety Net". The cart drawer opens. Note the membership price in the drawer.',
            'Add a "Stain" plan to the cart and look at the membership line again.',
            'Remove the Stain plan and add a "Stain + Structure" plan instead; look at the membership line again.'],
          expected: 'The membership line reads $19.99/month in all three cases — no 50% off, no "Included $0". The paid membership covers used/other furniture; the one included with every protection plan is an automatic benefit, not a cart line (MEM-7, Aug-14 meeting).',
          source: 'MEM-7 Doug 14-ago; _lib/stripe.mjs (pickMembershipPrice, siempre full)' },
        { id: 'KSK-023', kind: 'happy', role: 'Anyone', title: 'Gift coupons can be bought from the membership section',
          steps: ['Scroll to the membership section (the "Repair Safety Net" area, not the cart).',
            'Find and click the "Request a gift coupon code →" link there.',
            'Read the three options in the pop-up.'],
          expected: 'A gift pop-up opens with three choices — Stain $29.97, Stain + Structure $59.97, Membership $59.97 (each is three months of the plan) — and lets you continue to payment.',
          why: 'The gift links live in the membership section, not inside the checkout drawer.',
          source: 'kiosk/index.html:1210,1230 (.js-gift-coupon in membership section), 2042-2075' },
        { id: 'KSK-024', kind: 'edge', role: 'Associate', tech: true, title: 'A tampered saved cart is cleaned up, not trusted',
          steps: ['This case checks the kiosk ignores a faked cart. Press F12 to open developer tools, click the "Console" tab.',
            'Paste and run: localStorage.setItem("furnfx_cart", JSON.stringify([{cov:"stain",term:"monthly",count:9999,price:0.01}]))',
            'Reload the page and open the cart (top-right button).'],
          expected: 'The plan count is brought down to a sane maximum (not 9,999) and the price shows the real $9.99, never the fake $0.01 the pasted data claimed.',
          source: 'kiosk/index.html loadCart re-validates untrusted storage' }
      ]
    },
    {
      id: 'form',
      title: '3 · Checkout form (store fields)',
      cases: [
        { id: 'KSK-040', kind: 'validation', role: 'Associate', needs: ['associate'], title: 'Removing the plan should hide the store fields (kit-only cart)',
          steps: ['Add one "Stain" plan AND one care kit to the cart.',
            'Open the cart drawer (top-right button). Note that the store fields appear (sales order #, ZIP, delivery date, receipt photo).',
            'In the drawer, remove the Stain plan by tapping its "×", leaving only the kit.',
            'Look at whether the store fields (sales order #, ZIP, date, receipt photo) are still showing.'],
          expected: 'With only a kit left, those store fields should disappear (a kit needs no receipt). Fail this case if they stay on screen — and note whether the drawer then blocks you from paying for the kit because of "missing" fields.',
          why: 'A kit-only cart does not require store fields on the server; if the form still requires them, the sale is blocked.',
          source: 'kiosk/index.html:2467-2470 (remove handler skips cartFillSummary), :2440-2446 (the toggle); validate.mjs:158-166' },
        { id: 'KSK-041', kind: 'validation', role: 'Associate', title: 'The accuracy checkbox unlocks the Pay button',
          steps: ['With a plan in the cart, open the drawer and fill in the fields with any valid data.',
            'Leave the checkbox "I read the information above and it is accurate" UNCHECKED and look at the Pay button.',
            'Now check that box.'],
          expected: 'The Pay button is greyed out / not clickable until the accuracy box is checked; checking it enables the button.',
          source: 'KIOSK-3 Doug 02-jul; kiosk/index.html:2545-2558' },
        { id: 'KSK-042', kind: 'validation', role: 'Associate', title: 'Field checks: name, email, phone, ZIP, date',
          steps: ['With a plan in the cart, open the drawer.',
            'Try each of these, one at a time, and tap outside the field: name "Bob 99"; email "x@y"; phone "123"; ZIP "1234".',
            'Then open the delivery-date picker and try to pick a date about three months ago.',
            'Finally fill everything correctly (a real 10-digit phone, ZIP like 84321, a date within the last 60 days).'],
          expected: 'Each wrong value shows a short message (a name cannot contain numbers; the phone needs several digits; the ZIP should be 5 digits). The date picker will not let you go earlier than 60 days ago (that is the eligibility window). Correct values are accepted.',
          why: 'The 60-day floor and the 7-digit phone minimum are intentional (phone must also allow international numbers).',
          source: 'kiosk/index.html:2749-2757 (date min −60), validate.mjs:54-63 (phone ≥7), :144-150 (date window)' },
        { id: 'KSK-043', kind: 'validation', role: 'Associate', title: 'A too-short name should be flagged clearly',
          steps: ['With a plan in the cart and the rest of the form valid, type a single-letter name like "J".',
            'Check the accuracy box and try to pay.'],
          expected: 'The name should be flagged right at the name field with a clear message BEFORE anything is sent. Fail this case if the only feedback is a small code-like message at the very bottom after a delay, or if nothing obvious tells you the name is too short.',
          source: 'kiosk/index.html:3027 (no length check client-side), :3122 (raw code note); validate.mjs:127' },
        { id: 'KSK-044', kind: 'happy', role: 'Associate', needs: ['associate'], title: 'The associate # is remembered on this device',
          steps: ['Complete any sale (or just fill the associate # field with the value in the "Test data" box below and pay a kit with the test card).',
            'After the success screen, tap "Start a new purchase" and open the cart form again.'],
          expected: 'The associate # field is already filled with the same value you used, so the associate does not retype it. All the customer fields are empty and the accuracy box is unchecked again.',
          source: 'KIOSK-7; kiosk/index.html:3397-3427' },
        { id: 'KSK-045', kind: 'validation', role: 'Associate', title: 'An unknown referral code never blocks the sale',
          steps: ['Make sure you are on the plain kiosk (no "Selling as…" badge in the bottom-left).',
            'Open the cart drawer. Scroll to the "Dealer referral code (optional)" field near the bottom.',
            'Type NOTACODE and tap outside the field.',
            'If the team gave you a real dealer code, try that too.'],
          expected: 'An unknown code shows "Code not recognized — you can still check out." and you can still pay. A real code shows "Code applied — supporting <dealer name>." Valid codes come from the portal (Referral Codes screen); you cannot make one up.',
          why: 'Referral codes are created by RAP admins in the portal; a wrong or disabled code is ignored but never stops a sale.',
          source: 'kiosk/index.html:2726-2745; referral-validate.mjs; Doug 15-jul' }
      ]
    },
    {
      id: 'receipt',
      title: '4 · Receipt photo',
      cases: [
        { id: 'KSK-060', kind: 'validation', role: 'Associate', title: 'Taking a receipt photo on the tablet',
          steps: ['With a plan in the cart, open the drawer and find the receipt photo area.',
            'Tap it and try to TAKE a photo of a printed receipt (not pick one from the gallery).',
            'Note what your device offered: camera, gallery, or both. Say which device and browser you used.'],
          expected: 'You can attach a clear photo of the receipt. Known rough edge to record: on some Android tablets the picker opens straight to the gallery with no "take a photo" option, while iPad offers Take Photo / Photo Library / Choose File. Note exactly what you saw on your device.',
          why: 'The camera option is left to the device on purpose so the customer can also pick from their gallery; Android sometimes hides the camera.',
          source: 'kiosk/index.html:1566 (no capture attribute, by design)' },
        { id: 'KSK-061', kind: 'validation', role: 'Associate', title: 'Non-image files are refused',
          steps: ['In the receipt photo area, try to attach a PDF, or a text file renamed to look like an image.'],
          expected: 'It is refused with a message like "Please choose an image of your receipt." You cannot check out without a real image.',
          source: 'kiosk/index.html:2933; upload-receipt.mjs (image byte check, 2MB cap)' },
        { id: 'KSK-062', kind: 'happy', role: 'Associate + Customer', title: 'Adding the receipt from the customer\'s phone',
          steps: ['In the receipt area, tap "Add the receipt from a phone".',
            'Scan the QR code that appears with a phone, and photograph the receipt there.',
            'Watch the tablet screen while the phone uploads.',
            'On the PHONE, check whether the small preview of the photo shows correctly after upload. Say which phone and browser.'],
          expected: 'After the phone uploads, the tablet swaps the QR for the receipt thumbnail on its own within a few seconds, and checkout can continue. Known rough edge to confirm: on some phones the little preview thumbnail shows broken even though the upload worked — note if you see that.',
          source: 'kiosk/index.html:3169-3233 (receipt-only handoff); :4242 (preview from raw file)' },
        { id: 'KSK-063', kind: 'edge', role: 'Associate', title: 'No receipt arrives: the wait should say so clearly',
          steps: ['Tap "Add the receipt from a phone" and then do nothing for about 3 minutes.',
            'Watch the receipt area closely (not just the bottom of the form).'],
          expected: 'After the wait, a clear message like "Still no receipt from the phone — tap the option again to retry" should appear right where the QR was. Note whether the message actually appears there, or whether the QR just closes with no visible explanation.',
          source: 'kiosk/index.html:3200-3206 (message goes to the footer note, far from the QR)' }
      ]
    },
    {
      id: 'pay',
      title: '5 · The four ways to pay',
      cases: [
        { id: 'KSK-080', kind: 'happy', role: 'Associate', title: 'The four payment options and their button text',
          steps: ['With a valid plan checkout ready, look at the "Ways to pay" choices near the bottom of the drawer.'],
          expected: 'Four options: "Pay on this device" (selected by default), "Show QR to add receipt and pay", "Show QR to pay", and "Email the link". The big button\'s wording changes with your choice (for example "Show the QR code" or "Email the payment link").',
          source: 'kiosk/index.html:1605-1613, 3009' },
        { id: 'KSK-081', kind: 'happy', role: 'Associate + Customer', needs: ['associate','email'], title: 'Pay on this device, start to finish',
          steps: ['Build a cart with one "Stain + Structure" plan.',
            'Open the drawer, fill the form (use the associate # and customer email from the Test data box below), attach a receipt photo, pick a date within 60 days.',
            'Choose "Pay on this device", check the accuracy box, and pay with the test card.',
            'Read the screen you return to.'],
          expected: 'Stripe charges $19.99/mo. You come back to the kiosk\'s "Payment received" screen (large text, tells the plan holder to check their email, mentions the spam folder and the phone 1-833-395-7824). The cart empties. Tapping "Start a new purchase" opens a fresh kiosk.',
          source: 'KIOSK-21 success view; _lib/checkout.mjs return URLs' },
        { id: 'KSK-082', kind: 'happy', role: 'Associate + Customer', needs: ['email'], title: 'One QR for receipt AND payment on the phone',
          steps: ['Start a new sale with one plan. Fill the form (use the Test data email below). Choose "Show QR to add receipt and pay" — note the receipt area on the tablet disappears, which is correct.',
            'Submit, then scan the QR with a phone.',
            'On the phone: read what it shows, photograph the receipt, then pay with the test card.',
            'Watch the tablet the whole time.'],
          expected: 'The phone page greets the customer by first name only (no address or email shown), lists the plan and total, and will not show a Pay button until the receipt photo is attached. After the phone pays, the tablet moves to the success screen by itself. One QR did both the receipt and the payment.',
          source: 'G16 single-QR handoff; kiosk/index.html:4171-4280' },
        { id: 'KSK-083', kind: 'validation', role: 'Associate', title: 'A new sale should reset "Ways to pay" to the default',
          steps: ['Finish any sale so you reach the "Payment received" screen.',
            'Tap "Start a new purchase".',
            'Build a new cart, open the drawer, and look at which "Ways to pay" option is selected.'],
          expected: '"Pay on this device" should be selected again (the default). Fail this case if it stays on whatever you picked in the previous sale.',
          source: 'kiosk/index.html:3406-3418 (resetKioskFields does not reset the deliver radios)' },
        { id: 'KSK-084', kind: 'validation', role: 'Associate + Customer', needs: ['email'], title: 'Email the payment link',
          steps: ['Start a new sale with one plan. Fill the form using the Test data email below. Choose "Email the link" and submit.',
            'Read the tablet message, then check that email inbox (and spam).'],
          expected: 'The tablet should say the link was sent to that address, and the email should arrive. Known environment note: if payment-link email is not switched on in this environment, the tablet instead shows a QR with "We couldn\'t email the link — scan or tap this code instead." That is a settings gap, not a broken button; record which message you saw.',
          source: '_lib/checkout.mjs:188-207 (email path); _lib/email.mjs (needs RESEND_API_KEY + FROM_EMAIL)' },
        { id: 'KSK-085', kind: 'edge', role: 'Associate', title: 'Nobody pays: the waiting screen options',
          steps: ['Start a "Show QR to pay" payment and let it sit for about 3 minutes without paying.',
            'Read what the screen offers, and try the "×" close button on that waiting panel.'],
          expected: 'After the wait it says the payment has not come through yet and offers "Check again", "Choose another way to pay", and "Start a new purchase". Note if the stale QR and link stay on screen (they should ideally hide), and note whether the "×" closes the whole cart (which is confusing) instead of just going back to the form.',
          source: 'kiosk/index.html:3247-3264, 1565-1580' },
        { id: 'KSK-086', kind: 'edge', role: 'Customer', title: 'Old and unknown payment links say the right thing',
          steps: ['Take a "/p/..." short link from an earlier, already-paid sale and open it again on a phone.',
            'Then open a made-up one: {BASE}/p/ZZZZZZZZ.'],
          expected: 'The old link says the checkout is done or expired; the made-up one says "Payment link not found — check the code and try again, or ask the store associate to start a new sale." Neither can reach a payment.',
          source: 'pay-redirect.mjs:32-53 (404 vs 410)' },
        { id: 'KSK-087', kind: 'edge', role: 'Customer', title: 'Reusing a paid QR cannot charge twice',
          steps: ['Right after finishing a "Show QR to add receipt and pay" sale, scan that SAME QR again on the phone.'],
          expected: 'The phone shows a done/expired panel; tapping Pay again reopens the same completed payment, never a second charge.',
          source: 'kiosk-handoff-complete (idempotent); token TTL 15 min' },
        { id: 'KSK-088', kind: 'edge', role: 'Customer', title: 'On the phone, no Pay button until the receipt is attached',
          steps: ['In a "Show QR to add receipt and pay" sale for a plan, on the phone look for a Pay button BEFORE photographing the receipt.'],
          expected: 'There is no Pay button until you attach the receipt photo. (Kit-only handoffs correctly skip the receipt and show Pay right away.)',
          source: 'kiosk/index.html:4219 (payBtn.hidden = !attached)' }
      ]
    },
    {
      id: 'post',
      title: '6 · After the sale',
      cases: [
        { id: 'KSK-100', kind: 'happy', role: 'Associate', title: 'The kiosk resets itself between customers',
          steps: ['Reach the "Payment received" screen and wait two minutes without touching anything.'],
          expected: 'The cart is empty right after success, and after about two minutes the screen returns to a fresh sale on its own, so the next customer never sees the previous one\'s details.',
          source: 'kiosk/index.html:3237 (120s auto-reset)' },
        { id: 'KSK-101', kind: 'happy', role: 'Customer', title: 'The customer gets a contract number',
          steps: ['After a plan sale, look for a contract number (like RX-10001) on the confirmation, the welcome email, or the customer dashboard.'],
          expected: 'A contract number in the form RX-##### is created for a plan sale. Note the exact format you see. (Whether the first cycle should also show a "-01" suffix is a formatting decision under review — just record what appears.)',
          source: '_lib/portal.mjs:142-146 (contractNumber); stripe-webhook master_no' },
        { id: 'KSK-102', kind: 'access', role: 'Dealer', title: 'The sale shows up under the right dealer',
          openInWindow: 'Subscription Portal',
          steps: ['Sell one plan either via the sales-mode link (KSK-003) or the "Selling as" badge (KSK-002), typing a memorable associate # such as A-77. Complete a test payment.',
            'In a separate window, sign into the portal as the Dealer owner (owner@rapqa.com / 12345678).',
            'Open "Subscribers" in the left menu; also open "Dashboard".',
            'Give it one to two minutes and refresh.'],
          expected: 'Within a couple of minutes the new subscription appears under Summit with associate A-77, and the Dashboard "Active subscribers" count reflects it. As a check: a sale made on the PLAIN kiosk (no badge, no code) does NOT appear under Summit.',
          source: 'attribution _lib/checkout.mjs:56-64; associate copied stripe-webhook.mjs:273; portal-subscribers.mjs' },
        { id: 'KSK-103', kind: 'access', role: 'Admin + Dealer', title: 'A switched-off dealer cannot sell through its session',
          openInWindow: 'Subscription Portal',
          steps: ['In a separate window, sign into the portal as the RAP admin (admin@raptns.com / 12345678). Pick "Summit Home Furnishings" in the top dropdown and open "Dealer Admin".',
            'Turn the "Sell through kiosk" switch OFF.',
            'Now open Summit\'s sales-mode link (or "Open kiosk signed in" as the owner), build a plan, and try to pay.',
            'When done, turn "Sell through kiosk" back ON.'],
          expected: 'The checkout is refused (the sale does not go through). For contrast, that same dealer\'s referral CODE typed on the plain kiosk would simply be ignored while the sale still completes. Both behaviors are intended.',
          source: '_lib/checkout.mjs:71-79 (sell-time gate); _lib/referral.mjs:45-49' }
      ]
    },
    {
      id: 'xsite',
      title: '7 · Cross-site: kiosk ↔ portal',
      cases: [
        { id: 'KSK-XS-01', kind: 'access', role: 'Admin', title: 'A code made in the portal works on the kiosk and counts back',
          openInWindow: 'Subscription Portal',
          steps: ['In a separate window, sign into the portal as the RAP admin. Pick "Summit Home Furnishings" in the top dropdown.',
            'Open "Referral Codes" and click "Generate code". Copy the new code (looks like SUM-7K2M).',
            'On the kiosk (plain, no badge), open the cart drawer, type that code in the "Dealer referral code" field, and tap outside it.',
            'Complete a plan purchase with the test card.',
            'Back in the portal Referral Codes screen (Summit selected), refresh after a minute or two.'],
          expected: 'On the kiosk the code shows "Code applied — supporting Summit Home Furnishings." After the sale, that code\'s "Uses" and "Attributed subs" go up by one in the portal. (The dollar "Credit earned" only moves if commission tracking is switched on in this environment — $0 there is expected.)',
          source: 'portal-referral-codes.mjs:76-103; referral-validate.mjs; referralStats _lib/referral.mjs:83-99' },
        { id: 'KSK-XS-02', kind: 'access', role: 'Admin', title: 'Regenerating the sales link kills the old one',
          openInWindow: 'Subscription Portal',
          steps: ['In the portal (admin, Summit selected), open Dealer Admin and note the current sales-mode address (call it OLD).',
            'Click the sales-mode button again (now "Regenerate link"); a NEW address appears.',
            'In a separate window, open the OLD address, then the NEW one.'],
          expected: 'The OLD address shows "Sales link not found" (a 404 page). The NEW address opens the kiosk "Selling as Summit" correctly.',
          source: 'portal-sales-mode.mjs:60-63,74-88; sales-mode-redirect.mjs:51-58' },
        { id: 'KSK-XS-03', kind: 'access', role: 'Admin', title: 'Turning the dealer off the reports hides it from the totals',
          openInWindow: 'Subscription Portal',
          steps: ['In the portal (admin), set the top dropdown to "All", open the Dashboard and Subscribers, and note the totals (Summit is included).',
            'Set the dropdown to "Summit", open Dealer Admin, and turn "Include in admin reports" OFF.',
            'Set the dropdown back to "All" and reopen the Dashboard and Subscribers.',
            'Then set the dropdown to "Summit" alone.',
            'When done, turn "Include in admin reports" back ON.'],
          expected: 'With the switch off, Summit\'s numbers and rows drop out of the "All" totals, but viewing Summit on its own still shows everything (nothing was deleted).',
          source: 'include_in_rollups; _lib/portal.mjs:66-76 applied across stats/subscribers' },
        { id: 'KSK-XS-04', kind: 'happy', role: 'Customer + Dealer', needs: ['associate','email'], title: 'A new buyer can sign in AND appears under the dealer',
          openInWindow: 'Subscription Portal',
          steps: ['Sell one plan as the dealer (via KSK-002 or KSK-003), using the associate # and the fresh customer email from the Test data box below. Complete the test payment.',
            'Within a minute or two, open that email inbox: you should get a Furniture-Rx welcome email with a temporary password.',
            'Open {BASE}/../account.html (the customer sign-in page) and sign in with that email and the temporary password.',
            'In a separate window, sign into the portal as the Dealer owner and open Subscribers.'],
          expected: 'On the customer side you are made to set a new password before seeing anything, then you see the plan you just bought. On the dealer side, that same customer appears in Summit\'s Subscribers with the associate # you used.',
          source: 'stripe-webhook.mjs:144-177 (account+welcome); account.html forced change; portal-subscribers.mjs' }
      ]
    },
    {
      id: 'abuse',
      title: '8 · Edge & abuse',
      cases: [
        { id: 'KSK-120', kind: 'access', role: 'Attacker-ish', tech: true, title: 'Server secrets are not served',
          steps: ['Open {BASE}/.env in the address bar.',
            'To see the real result, open developer tools (F12) → the "Network" tab, then reload {BASE}/.env and click the ".env" request to read its status.'],
          expected: 'The response status is 404 (Not Found). The page you SEE is the normal kiosk home page, because a 404 can still show a friendly page — that is fine. What matters: the response never contains a file of keys (no lines like KEY=value). It is safe.',
          why: 'A 404 with the home page as its body looks like "no 404" in the address bar, but the status really is 404 and no secret is exposed.',
          source: 'kiosk/netlify.toml:24-34 (forced 404); verified live' },
        { id: 'KSK-121', kind: 'edge', role: 'Attacker-ish', title: 'A broken phone link should say "expired", not show the upload screen',
          steps: ['On a phone (or any browser), open {BASE}/?h=garbage.',
            'Then open {BASE}/?h= (nothing after the =).'],
          expected: 'Both should land on a simple "this code expired / ask your associate for a new one" screen. Known bug to confirm: with "garbage" it instead shows the full "take a photo of your receipt" screen and only fails ("That didn\'t upload") AFTER you add a photo. (The empty one is handled correctly.) Nothing can actually reach a payment either way.',
          source: 'kiosk/index.html:4287-4298 (load ignores the error), :4149 (empty handled)' },
        { id: 'KSK-122', kind: 'edge', role: 'Associate', title: 'Rate limits behave like a short wait, not a wall',
          steps: ['Start a checkout, cancel on the Stripe page, and repeat quickly six or more times within a minute.'],
          expected: 'Around the sixth try the Pay button briefly disables with "Too many attempts — please wait a few seconds and try again." and comes back on its own. The sale is not lost.',
          source: 'create-checkout-session 5/60s; kiosk/index.html:3114-3119' },
        { id: 'KSK-123', kind: 'edge', role: 'Associate', title: 'Double-tapping Pay does not double-charge',
          steps: ['With a valid checkout ready, tap the Pay button twice as fast as you can.'],
          expected: 'Only one checkout starts (one Stripe page, one charge). Record anything else you notice.',
          source: 'single submit handler + server idempotency' },
        { id: 'KSK-124', kind: 'edge', role: 'Associate', title: 'Switching payment method should keep the receipt already taken',
          steps: ['Start a "Show QR to add receipt and pay" sale. Have the "customer" scan the QR and photograph the receipt on the phone, but do NOT pay yet.',
            'On the tablet, tap "Choose another way to pay", then finish with "Pay on this device".'],
          expected: 'The receipt the customer already photographed should carry over so you can finish paying on the tablet. Fail this case if the receipt is lost and you are asked to add it again.',
          source: 'kiosk/index.html:3384-3391 (poll never stores receipt_path), :3071-3096 (checkout then fails)' },
        { id: 'KSK-125', kind: 'edge', role: 'Associate', title: 'Reloading mid-checkout: what survives',
          steps: ['Fill the whole form (no payment yet) and reload the page.',
            'Reopen the cart and the form.'],
          expected: 'The cart items and the associate # survive the reload. The typed customer details (name, email, phone, address, order #, ZIP, date) are cleared — that is on purpose (personal data is never stored on a shared tablet). Record exactly what remained.',
          why: 'Personal data is intentionally kept out of the browser\'s storage; the cart and associate # are not personal so they persist.',
          source: 'kiosk/index.html:2169-2171 (cart persists), :3400-3412 (associate), :3406-3417 (PII cleared)' },
        { id: 'KSK-126', kind: 'edge', role: 'Associate', title: 'Tablet and phone screen sizes',
          steps: ['Try the full flow at tablet size and at phone size: plan cards, cart drawer, form, ways-to-pay, the QR screen.'],
          expected: 'No sideways scrolling, the QR fully visible, the form usable with the on-screen keyboard open, every button reachable.',
          source: 'responsive expectation' },
        { id: 'KSK-127', kind: 'edge', role: 'Associate', tech: true, title: 'Spotty store Wi-Fi during checkout',
          steps: ['Open developer tools (F12) → Network tab → set it to "Offline". Try to pay.',
            'Set it back to "Online" and retry.',
            'Also try going Offline during a QR wait, then back Online.'],
          expected: 'A readable error appears (never a frozen button or blank screen). Once the network is back, retrying works without rebuilding the cart, and the QR wait resumes.',
          source: 'poll + retry design' }
      ]
    }
  ]
};
