// Furniture-Rx QA suite — D2C storefront (root index.html + account.html).
// Evidence-based: index.html, account.html, netlify/functions, Doug decisions in misc/.
export default {
  appId: 'furnfx-qa-d2c',
  title: 'Furniture-Rx QA — D2C Storefront',
  version: '2026-07-29',
  envs: [
    { id: 'live', label: 'Live', base: 'https://www.furniturerx.net' },
    { id: 'local', label: 'Localhost (netlify dev)', base: 'http://localhost:8888' }
  ],
  intro: [
    'This is the public store at furniturerx.net: protection plans (Stain $9.99/mo, Stain + Structure $19.99/mo), the Repair Safety Net membership, care kits, gift coupons, and the Maya chat assistant.',
    'Before paying anything, check with the team that the site is in Stripe TEST mode. Test card: `4242 4242 4242 4242`, any future expiry date, any 3-digit code, any ZIP.',
    'When a case shows a "Test data for this case" box, tap the email chip to copy the fresh address it made for you. Each purchase creates an account for that email, so you want a brand-new one every time — do not invent your own.',
    'Plan purchases need a receipt photo: any clear photo of a paper receipt works, so photograph any printed page.',
    'The purchase date must be within the last 60 days (or up to 90 days ahead for a scheduled delivery).',
    'Between purchase cases, empty the cart (the drawer has an "Empty cart" button) so each case starts clean.'
  ],
  sections: [
    {
      id: 'landing',
      title: '1 · Landing, navigation & static content',
      cases: [
        { id: 'D2C-001', kind: 'happy', role: 'Anonymous', title: 'Home page loads with all main sections',
          steps: ['Open {BASE}/ in a fresh private/incognito window (a window that starts with no history or saved logins).',
            'Scroll slowly from the top of the page all the way to the bottom.'],
          expected: 'As you scroll you pass, in this order: the hero banner with the plan builder, the two plan comparison cards, a row of trust badges, a preview of the customer dashboard, the FAQ, the care kits, the Repair Safety Net membership section, and the footer. A round chat button floats in a bottom corner. No images are broken and nothing on the page looks obviously missing.',
          source: 'index.html section order; CLAUDE.md layout' },
        { id: 'D2C-002', kind: 'access', role: 'Anonymous', title: 'Dashboard nav link is hidden for visitors',
          steps: ['In the same private window (still signed out), look at the menu across the top of the page, then open the menu again on a narrow, phone-width window.'],
          expected: 'There is NO "Dashboard" item in the menu (it only appears once you are signed in). The menu shows Protection, Repair Safety Net, Care kits, and FAQ.',
          source: 'index.html:66,89 + account-me check (2506-2534)' },
        { id: 'D2C-003', kind: 'happy', role: 'Anonymous', title: 'Cart badge counts total units',
          steps: ['On the Stain card, press "+" until the count reads 2, then press "Save to cart".',
            'Add one care kit and add the Repair Safety Net membership.',
            'Look at the small number badge on the cart button (top-right of the header).'],
          expected: 'The badge shows 4 (2 plans + 1 kit + 1 membership): it adds up every unit in the cart. When the cart is empty the badge disappears completely.',
          source: 'index.html:2327-2335 (badge = Σ plan counts + Σ kit qty + membership)' },
        { id: 'D2C-004', kind: 'validation', role: 'Anonymous', title: 'Known dead links: footer and referral section',
          steps: ['Scroll to the "refer a friend" section and click "Get your referral link".',
            'In the footer, click each of these in turn: File a claim, Manage coverage, Contact concierge, Terms of service, Privacy policy, Accessibility.'],
          expected: 'KNOWN state to confirm: every one of these does nothing when clicked (they are placeholders that are not wired up yet). The one exception is the "Log in" link in the footer, which does work and opens the account sign-in page. Note anything that now behaves differently.',
          source: 'index.html:734, 763-774 (href="#" no-ops); footer Log in :762' },
        { id: 'D2C-005', kind: 'happy', role: 'Anonymous', title: '/dashboard and /login shortcuts',
          steps: ['Type {BASE}/dashboard straight into the address bar.',
            'Then type {BASE}/login straight into the address bar.'],
          expected: 'Both send you to the account sign-in page.',
          source: 'netlify.toml:56-67 (301 redirects, DASH-5/AUTH-1)' },
        { id: 'D2C-006', kind: 'happy', role: 'Anonymous', title: 'Terms page reachable from every T&C link',
          steps: ['Click any "terms and conditions" link on the page (in the plan fine print, in the checkout drawer, or in the FAQ).'],
          expected: 'Each one opens a real Protection Plan terms and conditions page, not a dead link.',
          source: 'index.html:371,465,773,891 → /terms/' }
      ]
    },
    {
      id: 'config',
      title: '2 · Configurator & plan cards',
      cases: [
        { id: 'D2C-020', kind: 'happy', role: 'Anonymous', title: 'Monthly prices and coverage figures',
          steps: ['In the hero plan builder at the top, choose Stain, then Stain + Structure, keeping the term on Monthly.',
            'Scroll down and compare the prices with the two cards in the comparison section.'],
          expected: 'Stain is $9.99/mo and Stain + Structure is $19.99/mo, both covering "up to $5,000". The hero and the cards always show the same prices.',
          source: 'index.html:1248-1252 PLANS; CLAUDE.md pricing (server canonical 999/1999 cents)' },
        { id: 'D2C-021', kind: 'happy', role: 'Anonymous', title: 'Hero and card steppers are the SAME counter',
          steps: ['On the Stain card, press "+" until the stepper reads 3.',
            'Scroll up to the hero plan builder and read its count.',
            'In the hero, press "+" once, then scroll back down to the Stain card.'],
          expected: 'After the card edit the hero reads 3 and has switched itself to Stain. After the hero edit the card reads 4. They are one shared cart line and stay in sync.',
          source: 'index.html:1327-1382 (hero count derived from cart line); reflectToHero 1519-1527' },
        { id: 'D2C-022', kind: 'validation', role: 'Anonymous', title: 'No artificial cap: stepper goes far past 2',
          steps: ['Press "+" on a plan stepper 15 times in a row.'],
          expected: 'The count keeps climbing freely, well past 2. The price multiplies with the count and the coverage note reads "N plans · $5,000 each".',
          why: 'There is no small limit on how many plans of one type a customer can buy.',
          source: 'MAX_COUNT=99 (index.html:1253); Doug 18-jun "buy any number"' },
        { id: 'D2C-023', kind: 'validation', role: 'Anonymous', title: 'Yearly is a preview, never purchasable',
          steps: ['In the hero, switch the term to 1 year, then to 3 years.',
            'Try to use the "+"/"−" stepper and try to find a Checkout button while on a yearly term.',
            'Switch back to Monthly.'],
          expected: 'On the yearly terms the prices are shown for comparison ($129.99/$259.99 for 1 year, $249.99/$449.99 for 3 years, with $7,500/$10,000 coverage limits), but the stepper does not work, there is no Checkout button, and a note explains that yearly is not available to buy yet. Nothing yearly is ever added to the cart.',
          why: 'Yearly is preview-only for now; only monthly plans can actually be purchased.',
          source: 'CFG-10 display-only; index.html:1334-1375, 2045-2048; server rejects term_not_supported' },
        { id: 'D2C-024', kind: 'happy', role: 'Anonymous', title: 'Piece type is a label, not a price factor',
          steps: ['With Stain and Monthly selected, change the "what are you protecting?" choice between Furniture, Outdoor, Mattress, Rugs, and the others.',
            'Watch the price and the coverage limit as you change it.'],
          expected: 'The price and the $5,000 limit never change when you switch the type. The type is only a description of what you are covering.',
          source: 'index.html:1255-1256; Doug 15-jul SKU-not-Type (type is informative, never a gate)' },
        { id: 'D2C-025', kind: 'edge', role: 'Anonymous', title: 'Type dropdown with keyboard only',
          steps: ['Press Tab until the "what are you protecting?" dropdown is highlighted. Open it with Enter, move through the choices with the arrow keys, jump with Home and End, and close it with Escape.'],
          expected: 'The dropdown works fully with the keyboard alone. Escape closes it without changing the choice. If the dropdown is near the bottom of the window, the list opens upward so it is not cut off.',
          source: 'index.html:1393-1473 custom listbox' },
        { id: 'D2C-026', kind: 'happy', role: 'Anonymous', title: 'Save to cart / In cart states',
          steps: ['On a card with a count of 1 or more, press "Save to cart".',
            'Look at the button afterward.'],
          expected: 'The button changes to a greyed-out, un-clickable "✓ In cart", and a "✓ Saved" confirmation appears for a few seconds.',
          source: 'index.html:2678-2683, 2600-2612' },
        { id: 'D2C-027', kind: 'happy', role: 'Anonymous', title: 'Eligibility fine print under the cards',
          steps: ['Read the small print just below the two plan cards.'],
          expected: 'It states: the furniture must be new, from an authorized dealer, bought within the last 60 days; a sales order number and ZIP code are collected at checkout; a receipt is required; billing is monthly in advance; coverage starts 30 days after payment; and it is not available in all states.',
          source: 'index.html:371; QA-6 Doug 27-jul "Use 60 days"' },
        { id: 'D2C-028', kind: 'edge', role: 'Anonymous', title: 'Start over resets the configurator',
          steps: ['Set up something unusual in the hero builder (Stain + Structure, 5 plans, Rugs).',
            'Press "Start over".'],
          expected: 'Everything resets to Stain, Monthly, Furniture, count 1.',
          source: 'index.html:1491-1498' }
      ]
    },
    {
      id: 'cart',
      title: '3 · Cart drawer & persistence',
      cases: [
        { id: 'D2C-040', kind: 'happy', role: 'Anonymous', title: 'True zero: empty cart is honest',
          steps: ['Remove every line from the cart so it is completely empty.',
            'Open the cart drawer (the panel that slides in from the right when you tap the cart button) and read the pay button.'],
          expected: 'The pay button is greyed out and reads "Your cart is empty". There is no leftover 1-plan preview anywhere.',
          source: 'index.html:1664-1689 (empty → disabled); CLAUDE.md true-zero decision' },
        { id: 'D2C-041', kind: 'happy', role: 'Anonymous', title: 'Total splits monthly vs one-time',
          steps: ['Put 1 Stain plan and 1 care kit in the cart.',
            'Open the drawer and read the total and the pay button.'],
          expected: 'The total reads like "$9.99/mo + $49.99 one-time", and the button reads "Pay $59.98 today ($9.99/mo + $49.99 one-time)". Each line has an "×" to remove it.',
          source: 'index.html:1646-1689' },
        { id: 'D2C-042', kind: 'validation', role: 'Anonymous', title: 'Empty cart asks for confirmation',
          steps: ['With several items in the cart, press "Empty cart".',
            'When the confirmation dialog appears, choose Cancel. Then press "Empty cart" again and accept it.'],
          expected: 'A confirmation dialog appears. Cancelling keeps everything. Accepting clears every line and also clears the receipt photo you had attached.',
          source: 'index.html:2283-2287, 2274-2282' },
        { id: 'D2C-043', kind: 'happy', role: 'Anonymous', title: 'Cart survives reload and browser restart',
          steps: ['Build a mixed cart (some plans, a kit, and the membership).',
            'Reload the page. Then close the tab entirely and reopen {BASE}/.'],
          expected: 'The cart is identical every time. It is saved only in this browser, so nothing is kept on a server.',
          source: 'localStorage furnfx_cart / furnfx_kits / furnfx_membership (index.html:1293-1309)' },
        { id: 'D2C-044', kind: 'edge', tech: true, role: 'Anonymous', title: 'Tampered saved cart is sanitized',
          steps: ['This is a technical check. Press F12 to open developer tools and click the "Console" tab.',
            'Paste and run this line: localStorage.setItem("furnfx_cart", JSON.stringify([{cov:"stain",term:"year1",count:5},{cov:"gold",term:"monthly",count:2},{cov:"stain",term:"monthly",count:500,price:0.01}]))',
            'Reload the page and open the cart.'],
          expected: 'The faked yearly line and the unknown "gold" line are both thrown out. The Stain monthly line stays, but its count is brought down to a sane maximum and it shows the real $9.99, never the $0.01 the pasted data claimed.',
          source: 'loadCart validates untrusted storage (index.html:2344-2363)' },
        { id: 'D2C-045', kind: 'validation', role: 'Anonymous', title: 'Receipt fields appear only when a plan is in the cart',
          steps: ['Put ONLY a care kit in the cart, open the drawer, and look for the sales order #, ZIP, delivery date, and receipt photo fields.',
            'Add a Stain plan to the cart and look again.'],
          expected: 'With only a kit, those fields are not shown (a kit needs no receipt). Once a plan is in the cart, the sales order #, ZIP, delivery date, and receipt photo fields appear and are required.',
          source: 'index.html:1596-1603 (#cart-receipt-fields gated on plan lines)' },
        { id: 'D2C-046', kind: 'happy', needs: ['email'], role: 'Anonymous', title: 'Email my cart to myself',
          steps: ['Build any cart. In the drawer, type the email from the "Test data for this case" box below (tap the chip to copy it) into the email field.',
            'Press "Email my cart to myself".',
            'Check that inbox.'],
          expected: 'A confirmation appears: "Sent a copy of your cart to <email> — no payment taken.", and the email arrives with the right items and prices. If you press the button without an email typed first, it asks you to add one.',
          source: 'index.html:2237-2261; email-cart.mjs (3/min limit)' },
        { id: 'D2C-047', kind: 'edge', role: 'Anonymous', title: 'Canceled checkout returns with cart intact',
          steps: ['Start a checkout with any valid cart and form, get to the Stripe payment page (its web address starts with checkout.stripe.com), then use the back or cancel link on that page.'],
          expected: 'You come back to the store, the drawer reopens on the form with the message "Checkout canceled — your plan wasn\'t activated.", and the whole cart is still there. The web address is cleaned up (no leftover "?canceled=1").',
          source: 'index.html:2302-2310' }
      ]
    },
    {
      id: 'memkits',
      title: '4 · Membership & care kits',
      cases: [
        { id: 'D2C-060', kind: 'happy', role: 'Anonymous', title: 'Membership price never changes with the cart',
          steps: ['Add the membership ALONE to the cart and note its price in the drawer.',
            'Add a Stain plan and look at the membership line again.',
            'Swap the Stain plan for a Stain + Structure plan and look again.'],
          expected: 'The membership line reads $19.99/month in all three cases — no 50% off, no "Included $0". The paid membership covers used/other furniture; the one included with every protection plan is an automatic benefit, not a cart line. The Stripe payment page must charge the same $19.99.',
          source: 'MEM-7 (Doug 14-ago); index.html drawer membershipPrice(); server _lib/stripe.mjs (pickMembershipPrice)' },
        { id: 'D2C-061', kind: 'happy', role: 'Anonymous', title: 'Section copy matches the cart (MEM-7 closed the old mismatch)',
          steps: ['Read the membership section copy that talks about being "included with any protection plan".',
            'Compare it with the cart from the previous case.'],
          expected: 'The copy and the cart no longer contradict each other: "included with any protection plan" refers to the automatic benefit on the item you buy; the $19.99 cart line is the PAID membership for used/other furniture. Nothing on the page promises 50% off or "free for 6/12 months" anymore.',
          source: 'MEM-7 (Doug 14-ago) cerró el gap del audit F6; index.html cards + drawer' },
        { id: 'D2C-062', kind: 'happy', role: 'Anonymous', title: 'Membership is max one, no quantity',
          steps: ['Add the membership from its section, then try to add it again from a different "Add membership" button.'],
          expected: 'Every "Add membership" button changes to a greyed-out "✓ In cart". There is never a quantity stepper for the membership.',
          source: 'index.html:1712-1727, 1305-1310' },
        { id: 'D2C-063', kind: 'happy', role: 'Anonymous', title: 'Kits: three at $49.99, cap 20',
          steps: ['Look at the three care kits (Wood, Fabric & upholstery, Leather) and their prices.',
            'Push one kit\'s quantity stepper past 20.'],
          expected: 'All three kits are $49.99. The quantity stops at 20.',
          source: 'index.html:624-690, cap :3013/2375' },
        { id: 'D2C-064', kind: 'happy', role: 'Anonymous', title: 'Membership T&C modal',
          steps: ['Click "See membership details".',
            'Skim the text in the pop-up.'],
          expected: 'A full membership terms pop-up opens and closes properly. KNOWN ISSUE to confirm: it still contains fill-in placeholders like "[Insert Date]" and "[Insert support email]" — note where you see them.',
          source: 'index.html:956-1158; gap: placeholders at :964, 1154-1156 (QA-8)' }
      ]
    },
    {
      id: 'form',
      title: '5 · Checkout form validations',
      cases: [
        { id: 'D2C-080', kind: 'validation', role: 'Buyer', title: 'Submitting empty names every missing field',
          steps: ['Put a plan in the cart, open the drawer, leave the form completely empty, and press the pay button.'],
          expected: 'A "Missing: …" note lists every empty required field by name, each field also gets its own inline message, and the cursor jumps to the first empty field. Nothing is sent to payment.',
          source: 'index.html:1897-1920, 2033 focusFirst' },
        { id: 'D2C-081', kind: 'validation', role: 'Buyer', title: 'Name rules: digits blocked, everything else humanely allowed',
          steps: ['In the name field try "Mary 123". Then try "José Núñez-O\'Brien". Then try a single word, "Cher".'],
          expected: '"Mary 123" is rejected with a message like "Numbers don\'t belong in a name…". The accented, hyphenated, apostrophe name is accepted. The single word is accepted, at most with a gentle non-blocking hint, never a hard error.',
          why: 'A real customer name must never be blocked over its characters, because a false rejection costs a sale.',
          source: 'index.html:2040, 1876-1879; QA-7 (Jakob BUG-06): never blocklist name characters' },
        { id: 'D2C-082', kind: 'validation', role: 'Buyer', title: 'Email, phone and ZIP formats',
          steps: ['Try email "a@b" and submit. Try phone "12345" and submit. Try ZIP "1234", then "123456", submitting each.',
            'Then enter valid ones: a real email, a 10-digit phone number, ZIP "84321", and ZIP "84321-1234".'],
          expected: 'The invalid entries each show a specific inline message (the phone needs at least 7 digits; the ZIP should be 5 digits, or ZIP+4). As you type the phone it formats itself like (555) 123-4567 and never accepts letters. The valid values are all accepted.',
          source: 'index.html:1815-1843, 2034-2039' },
        { id: 'D2C-083', kind: 'validation', role: 'Buyer', title: 'Purchase date window: 60 days back, 90 forward',
          steps: ['Open the date picker on the delivery/purchase date field.',
            'Try to pick a date about 3 months ago, and one about 4 months ahead.',
            'Then pick a date about 2 weeks ago and continue.'],
          expected: 'The picker only allows dates from 60 days ago through 90 days ahead. Anything outside that cannot be picked (or is rejected if it is forced through). The date about 2 weeks ago is accepted.',
          source: 'ELIG_DAYS=60/HORIZON_DAYS=90 (index.html:1817-1825); server validate.mjs:138-150; Doug 27-jul' },
        { id: 'D2C-084', kind: 'validation', role: 'Buyer', title: 'Receipt photo: required, images only, 2 MB after compression',
          steps: ['With a plan in the cart, try to submit without a photo.',
            'Try attaching a PDF or a .txt file as the receipt.',
            'Attach a normal photo of a receipt and submit.'],
          expected: 'With no photo the sale is blocked and the receipt is named in the "Missing" list. A non-image file is rejected with a clear message. A normal photo uploads (the browser shrinks it first) and the checkout continues.',
          source: 'index.html:876, 1935-1968; upload-receipt.mjs 2MB + image sniffing' },
        { id: 'D2C-085', kind: 'validation', role: 'Buyer', title: 'Referral code is optional and never blocks',
          steps: ['Type "XXXX-9999" in the dealer referral code field and click elsewhere.',
            'Complete the purchase anyway.'],
          expected: 'The unknown code shows "Code not recognized — you can still check out." and the sale completes normally. With a REAL dealer code you instead see "Code applied — supporting <dealer>."',
          why: 'A wrong or switched-off referral code is ignored but must never stop a sale.',
          source: 'index.html:1794-1807; Doug 15-jul: invalid/disabled code never blocks the sale' },
        { id: 'D2C-086', kind: 'edge', role: 'Buyer', title: 'Rapid-fire checkouts hit a polite rate limit',
          steps: ['Start a checkout and cancel it, and repeat quickly 6 or more times within one minute.'],
          expected: 'Around the 6th try the pay button disables with "Too many attempts — please wait Ns and try again." and comes back on its own.',
          source: 'create-checkout-session 5/min; index.html:2109-2114' },
        { id: 'D2C-087', kind: 'edge', role: 'Buyer', title: 'Emoji and copy-paste chaos in text fields',
          steps: ['In the name field type "Ana 🌸 Flores". In the address field, paste a value with a line break in the middle, then a very long 300-character address.'],
          expected: 'The emoji name is accepted (only digits are blocked). Very long values are trimmed on the server (the address is capped at 256 characters) instead of crashing. Nothing breaks visually. Note anything odd.',
          source: 'validate.mjs clean() length caps; name rule digits-only' }
      ]
    },
    {
      id: 'purchase',
      title: '6 · Purchase & post-purchase journey',
      cases: [
        { id: 'D2C-100', kind: 'happy', needs: ['email'], role: 'Buyer', title: 'Full plan purchase, end to end',
          steps: ['Cart: 1 Stain + Structure plan. Fill the form using the fresh email from the "Test data for this case" box below (tap to copy), plus valid data, a receipt photo, and a date within the last 60 days.',
            'Pay on the Stripe page with the test card.',
            'Read the screen you return to.'],
          expected: 'Stripe charges the $19.99/mo subscription. You return to the store and see "Payment received", a line that the sign-in information was sent to the email provided, a note about the spam folder, and the phone number 1-833-395-7824. The cart is now empty and the web address is clean (no leftover "?paid=1").',
          source: 'index.html:917-925 success copy (KIOSK-21); :2291-2298 clearCart on paid' },
        { id: 'D2C-101', kind: 'happy', needs: ['email'], role: 'Customer', title: 'Welcome email with temporary password',
          steps: ['Open the inbox of the email you just used.',
            'Find the welcome email and read it fully.'],
          expected: 'The subject is "Your FurnitureRx account is ready". It has a single button, "View my dashboard →", a temporary password shaped like XXXX-XXXX-XXXX, and a line saying you will be asked to choose your own password the first time you sign in.',
          source: '_lib/onboarding.mjs:31-53; MAIL-1 Doug 08-jul (one link only)' },
        { id: 'D2C-102', kind: 'happy', role: 'Customer', title: 'First login forces a password change, no skip',
          steps: ['Click the button in the welcome email. Confirm the sign-in form is already filled in with your email.',
            'Sign in using the temporary password.',
            'Look carefully for any way to skip the "choose a new password" step.'],
          expected: 'Sign-in succeeds and you are taken straight into "set a new password", with no skip option. A password under 8 characters is rejected. After you set one, you reach the dashboard.',
          source: 'account.html:901-935 (no Skip); auth-set-password PW_MIN=8; SEC-3a server-enforced' },
        { id: 'D2C-103', kind: 'access', tech: true, role: 'Customer', title: 'Temp password cannot bypass the forced change',
          steps: ['This is a technical check. Do a fresh purchase and sign in with the temporary password, but BEFORE setting the new password, press F12, open the "Network" tab, and copy the "Authorization" header from any API request.',
            'In the Console, run: fetch("/api/get-my-account",{headers:{Authorization:"Bearer <token>"}}).then(r=>r.status).then(console.log)'],
          expected: 'The response is 403 — the forced password change is enforced by the server, not just hidden on the screen.',
          source: '_lib/auth.mjs:35-45; SEC-3a' },
        { id: 'D2C-104', kind: 'happy', needs: ['email'], role: 'Customer', title: 'One-time code (OTP) recovery works',
          steps: ['Sign out. On the sign-in page choose "Email me a one-time code instead".',
            'Enter the code from the email.'],
          expected: 'A numeric code arrives by email and entering it signs you in. A wrong code shows "That code didn\'t work — check it or request a new one."',
          source: 'account.html:338-343, 927-941; auth-otp.mjs' },
        { id: 'D2C-105', kind: 'happy', role: 'Customer', title: 'Real dashboard replaces the marketing mock',
          steps: ['While signed in, open {BASE}/ and scroll to the dashboard section.'],
          expected: 'The preview is replaced by YOUR real coverage: the correct plan, price, status, and start date. An account with only a membership shows a separate "Your membership" card instead.',
          source: 'index.html:2916-2952 loadAccount; get-my-account.mjs' },
        { id: 'D2C-106', kind: 'edge', needs: ['email'], role: 'Customer', title: 'Clicking the email link before the account is ready',
          steps: ['On a NEW purchase, open the dashboard as fast as you can after paying (within seconds).'],
          expected: 'If the account is still being set up you see "Setting up your coverage…" and the page keeps retrying on its own (for about 7 seconds) instead of showing an error. Note how long it took.',
          source: 'index.html:2914-2945 retry/backoff for the webhook race' },
        { id: 'D2C-107', kind: 'access', needs: ['email'], role: 'Customer', title: 'Signed-in checkout locks the buyer email',
          steps: ['While signed in, build a cart and open the checkout form.',
            'Try to edit the email field. Then press "Not you? Sign out".'],
          expected: 'The email field is locked and shows "Buying as <your email>". Signing out unlocks it and also hides the Dashboard menu item again.',
          source: 'index.html:844-845, 2525-2543' },
        { id: 'D2C-108', kind: 'edge', tech: true, role: 'Customer', title: 'Session expiry is handled gracefully',
          steps: ['This is a technical check. While signed in on {BASE}/, open the Console (F12) and run: sessionStorage.setItem("furnfx_session", JSON.stringify({access_token:"expired-garbage"})). Reload the page and scroll to the dashboard section.'],
          expected: 'The page notices the bad session and shows "Your session expired. Please use the link in your email again." There is no crash and no endless spinner; the preview returns to its marketing state.',
          source: 'index.html:2921-2924' }
      ]
    },
    {
      id: 'maya',
      title: '7 · Maya chat assistant',
      cases: [
        { id: 'D2C-120', kind: 'happy', role: 'Anonymous', title: 'Maya opens and quotes monthly prices only',
          steps: ['Open the chat (the floating chat button). Ask: "how much are the plans?"'],
          expected: 'She quotes ONLY the monthly prices: $9.99 Stain and $19.99 Stain + Structure, with $5,000 coverage. She stays friendly and on-brand.',
          source: 'chat.mjs:42-47 grounded facts' },
        { id: 'D2C-121', kind: 'validation', role: 'Anonymous', title: 'G13b: Maya refuses to quote yearly prices',
          steps: ['Ask Maya: "what does the 3-year plan cost?" and then insist: "just give me the yearly number".'],
          expected: 'She never states a yearly dollar amount; she points you to the plan cards on the page. Insisting does not break her.',
          source: 'Gate G13b; chat.mjs:48' },
        { id: 'D2C-122', kind: 'validation', role: 'Anonymous', title: 'Maya never interprets coverage or claims',
          steps: ['Ask Maya: "my dog scratched the couch, is that covered?" and then "will my claim be approved?"'],
          expected: 'She declines to judge coverage or claim outcomes and points you to the plan terms. She never promises approval.',
          source: 'MAYA-1 (Doug 04-jul "I can\'t comment on that"); chat.mjs:70-72' },
        { id: 'D2C-123', kind: 'happy', role: 'Anonymous', title: 'Big-order quote: 10% of retail, needs your phone',
          steps: ['Tell Maya: "I bought $30,000 of furniture, what would coverage cost?"',
            'Follow her flow; when she offers to have an agent call you, give a name and phone number.'],
          expected: 'The estimate is 10% of the retail amount ($3,000/year for this example), labeled as preliminary pending agent verification. Saving the callback requires a phone number.',
          why: 'The estimate is worked out by the system, not made up by the assistant.',
          source: 'chat.mjs QUOTE_RATE=0.10, save_quote_lead requires phone (:123-136)' },
        { id: 'D2C-124', kind: 'happy', needs: ['email'], role: 'Anonymous', title: 'Maya sizes coverage and pre-fills checkout',
          steps: ['From a plan card, click the "Maya · your sales assistant" trigger.',
            'Answer her questions (name, the email from the "Test data for this case" box below, phone, address, ZIP, order #, a total around $12,000, and a date).',
            'Follow the "Review & check out →" button she offers.'],
          expected: 'She recommends enough plans to cover the total (3 plans for $12,000, one per $5,000), sets the cart to that count, and the checkout form arrives pre-filled with what you told her (without overwriting a locked email). The "Done" recap appears only once.',
          source: 'coverage-policy.mjs (ceil/5000, cap 3); index.html:3169-3217' },
        { id: 'D2C-125', kind: 'edge', role: 'Anonymous', title: 'Chat abuse: spam and hostility',
          steps: ['Send 12 quick messages in a row. Then send some insults. Then paste a 1,000-character block of text.'],
          expected: 'A rate limit kicks in around the 11th message with "I\'m getting a lot of messages right now — give me about Ns…". She stays polite through the insults. The long paste does not crash the chat.',
          source: 'chat.mjs 10/min burst + 60/h; index.html:3111-3120' },
        { id: 'D2C-126', kind: 'validation', role: 'Anonymous', title: 'KNOWN ISSUE: offline fallback mentions yearly prices',
          steps: ['Only if you can reach it (for example on localhost with no chat key set, or if the chat errors out): trigger Maya\'s canned backup replies and read them.'],
          expected: 'KNOWN ISSUE to confirm: one of the canned backup replies mentions yearly terms and $7,500/$10,000 coverage, which contradicts the no-yearly rule. Mark this N/A if you cannot reach the backup replies.',
          source: 'index.html:3072 canned reply; backlog F3' }
      ]
    },
    {
      id: 'gift',
      title: '8 · Gift coupons',
      cases: [
        { id: 'D2C-140', kind: 'happy', role: 'Anonymous', title: 'Gift overlay: tiers and 3-month totals',
          steps: ['Open {BASE}/#gift, or click the gift link in the membership section.'],
          expected: 'Three options appear: Stain $9.99, Stain + Structure $19.99, and Membership $19.99, with 3-month totals of $29.97, $59.97, and $59.97.',
          source: 'index.html:2554-2561; e2e-d2c asserts $29.97/$59.97' },
        { id: 'D2C-141', kind: 'happy', needs: ['email'], role: 'Buyer', title: 'Buy a gift and receive the code',
          steps: ['Buy the cheapest gift with the test card, using the email from the "Test data for this case" box below.',
            'Check that email for the gift code.'],
          expected: 'A one-time charge of $29.97 goes through and a gift code arrives (in the style GIFT-XXXXXXXX). Per the manual it is good for 1 use, expires in 90 days, and is for new customers.',
          source: 'misc/gift-coupons-manual.html; create-gift-checkout.mjs' },
        { id: 'D2C-142', kind: 'happy', needs: ['email'], role: 'Gift recipient', title: 'Redeem the gift inside Stripe checkout',
          steps: ['As a NEW customer (a fresh email), start a normal monthly plan checkout for the same tier that was gifted.',
            'On the Stripe page, use "Add promotion code" and enter the gift code.'],
          expected: 'Stripe accepts the code and takes the discount off the first 3 months. There is deliberately no code box on our own site; the code is entered only on Stripe\'s page.',
          source: '_lib/checkout.mjs:158-162 allow_promotion_codes (subscription mode only)' },
        { id: 'D2C-143', kind: 'validation', needs: ['email'], role: 'Buyer', title: 'Gift limits and errors',
          steps: ['Try the gift form with the email "nope@". If you have time, buy or start 6 gifts using the SAME buyer email.'],
          expected: 'The bad email is rejected. The 6th unredeemed gift for one buyer email is refused (the limit is 5). If gifts are not switched on in this environment, you instead see "Gifts aren\'t available just yet." — note which one you saw.',
          source: 'create-gift-checkout.mjs: invalid_email, gift_limit 409, 503 not configured' }
      ]
    },
    {
      id: 'abuse',
      title: '9 · Access, security & URL games',
      cases: [
        { id: 'D2C-160', kind: 'access', role: 'Attacker-ish', title: 'Secrets and internal files are not served',
          steps: ['Open each of these in the address bar: {BASE}/.env, {BASE}/.env.production, {BASE}/CLAUDE.md, {BASE}/misc/backlog-furniturerx.html.'],
          expected: 'Every one is Not Found (or just shows the normal store page). Only the store, the account page, the terms page, and the kit images are published.',
          source: 'netlify.toml:22-44 SEC-1; scripts/build.mjs publishes an explicit whitelist' },
        { id: 'D2C-161', kind: 'access', tech: true, role: 'Attacker-ish', title: 'API rejects strangers',
          steps: ['This is a technical check. Open the Console (F12) on {BASE}/ and run these one at a time:',
            'fetch("/api/get-my-account").then(r=>r.status).then(console.log)',
            'fetch("/api/get-my-account",{headers:{Authorization:"Bearer nonsense"}}).then(r=>r.status).then(console.log)'],
          expected: 'Both return 401. No account data ever comes back without a valid sign-in token.',
          source: 'get-my-account.mjs:37-44' },
        { id: 'D2C-162', kind: 'access', role: 'Anonymous', title: 'Kiosk UI never leaks into a normal visit',
          steps: ['Open {BASE}/?kiosk=1 and notice the extra in-store fields (associate #, ways-to-pay options).',
            'Now open the plain {BASE}/ in the SAME tab and check whether those extra fields are gone.'],
          expected: 'The in-store fields appear ONLY with ?kiosk=1 and do not stick around: the next plain visit is a normal store with no associate field and no delivery options.',
          source: 'index.html:33-38 (no persistence, clears sticky flag)' },
        { id: 'D2C-163', kind: 'edge', tech: true, role: 'Anonymous', title: 'Junk in the URL is harmless',
          steps: ['Open {BASE}/?paid=1 with an empty cart. Then open {BASE}/?ref=<script>alert(1)</script>. Then open {BASE}/#access_token=fake123 and immediately look at the address bar.'],
          expected: 'There is no fake purchase, no pop-up ever appears, and the "#access_token" part is wiped from the web address right away. Everything keeps working.',
          source: 'index.html:2291-2298; :11-25 hash stripping; textContent-only rendering' },
        { id: 'D2C-164', kind: 'edge', role: 'Buyer', title: 'Double-click the pay button',
          steps: ['With a valid form ready, double-click the Pay button as fast as you can.'],
          expected: 'Only one checkout starts: one Stripe page and one charge. Note anything else you see.',
          source: 'Submit handler + server rate limit; observe' },
        { id: 'D2C-165', kind: 'edge', role: 'Buyer', title: 'Back button after payment',
          steps: ['After a successful purchase, press the browser Back button until you are back at the store.'],
          expected: 'The cart stays empty, and re-submitting an old form page cannot charge you again without rebuilding the cart.',
          source: 'clearCart on ?paid=1 (index.html:2291-2298)' },
        { id: 'D2C-166', kind: 'edge', role: 'Anonymous', title: 'Phone-width walkthrough',
          steps: ['Open developer tools and switch to phone/device mode at 360 px wide. Walk through: the plan builder, a card, the cart drawer, the form, and the chat.'],
          expected: 'There is no sideways scrolling, the drawer is usable, the chat panel fits, and the steppers are easy to tap. Note every visual defect along with the screen width where you saw it.',
          source: 'Responsive expectation (portal has a formal gate; D2C findings go to observations)' },
        { id: 'D2C-167', kind: 'edge', role: 'Buyer', title: 'Offline mid-checkout',
          steps: ['Fill in a valid form. Open developer tools, go to the Network tab, and set it to "Offline". Press Pay. Then restore the network and retry.'],
          expected: 'A readable error appears (not a dead, frozen button). After reconnecting, retrying works with the cart still intact.',
          source: 'Front surfaces checkout errors verbatim (index.html:2117)' }
      ]
    }
  ]
};
